### ISSUE TITLE
Multiple error with the index for gesture

### ISSUE THREAD

**Issue by quckslvr** [software-mansion/react-native-gesture-handler#1786]
## Description
was coding and receive this huge error in the console. all file are in JS and 

`Web Bundling complete 4330ms
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'RaceGestureType' (reexported as 'RaceGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
Web Bundling complete 413ms
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:66
"export 'FlingGestureType' (reexported as 'FlingGesture') was not found in './handlers/gestures/flingGesture'
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
> 66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:70
"export 'ForceTouchGestureType' (reexported as 'ForceTouchGesture') was not found in './handlers/gestures/forceTouchGesture'
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
> 70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
./node_modules/react-native-gesture-handler/lib/module/index.js:79
"export 'GestureStateManagerType' (reexported as 'GestureStateManager') was not found in './handlers/gestures/gestureStateManager'
  77 |   ExclusiveGestureType as ExclusiveGesture,
  78 | } from './handlers/gestures/gestureComposition';
> 79 | export { GestureStateManagerType as GestureStateManager } from './handlers/gestures/gestureStateManager';
  80 | export { NativeViewGestureHandler } from './handlers/NativeViewGestureHandler';
  81 | export type {
  82 |   RawButtonProps,
./node_modules/react-native-gesture-handler/lib/module/index.js:67
"export 'LongPressGestureType' (reexported as 'LongPressGesture') was not found in './handlers/gestures/longPressGesture'
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
> 67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:72
"export 'ManualGestureType' (reexported as 'ManualGesture') was not found in './handlers/gestures/manualGesture'
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
> 72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:71
"export 'NativeGestureType' (reexported as 'NativeGesture') was not found in './handlers/gestures/nativeGesture'
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
> 71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:65
"export 'PanGestureType' (reexported as 'PanGesture') was not found in './handlers/gestures/panGesture'
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
> 65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:68
"export 'PinchGestureType' (reexported as 'PinchGesture') was not found in './handlers/gestures/pinchGesture'
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
> 68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'RaceGestureType' (reexported as 'RaceGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:69
"export 'RotationGestureType' (reexported as 'RotationGesture') was not found in './handlers/gestures/rotationGesture'
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
> 69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'SimultaneousGestureType' (reexported as 'SimultaneousGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:64
"export 'TapGestureType' (reexported as 'TapGesture') was not found in './handlers/gestures/tapGesture'
  62 | export { GestureDetector } from './handlers/gestures/GestureDetector';
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
> 64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';`

## Steps To Reproduce

1. Create a new app
2.  and this happens in webpack

## Package versions

- React:
- React Native:
- React Native Gesture Handler:

**Comment by danielkv** [comment]
Having the same problem here. These are not errors, only warnings, but they show up every start.

It seems like the types were not found

**Comment by Swiftwork** [comment]
Noticing the exact same. Haven't started up the web version for a while, but noticed today. Does not seem to affect the runtime at all though.

**Comment by grean** [comment]
Same here for the web after importing that: ```import 'react-native-gesture-handler';``` accordingly to the documentation
```
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:66
"export 'FlingGestureType' (reexported as 'FlingGesture') was not found in './handlers/gestures/flingGesture'
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
> 66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:70
"export 'ForceTouchGestureType' (reexported as 'ForceTouchGesture') was not found in './handlers/gestures/forceTouchGesture'
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
> 70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
./node_modules/react-native-gesture-handler/lib/module/index.js:79
"export 'GestureStateManagerType' (reexported as 'GestureStateManager') was not found in './handlers/gestures/gestureStateManager'
  77 |   ExclusiveGestureType as ExclusiveGesture,
  78 | } from './handlers/gestures/gestureComposition';
> 79 | export { GestureStateManagerType as GestureStateManager } from './handlers/gestures/gestureStateManager';
  80 | export { NativeViewGestureHandler } from './handlers/NativeViewGestureHandler';
  81 | export type {
  82 |   RawButtonProps,
./node_modules/react-native-gesture-handler/lib/module/index.js:67
"export 'LongPressGestureType' (reexported as 'LongPressGesture') was not found in './handlers/gestures/longPressGesture'
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
> 67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:72
"export 'ManualGestureType' (reexported as 'ManualGesture') was not found in './handlers/gestures/manualGesture'
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
> 72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:71
"export 'NativeGestureType' (reexported as 'NativeGesture') was not found in './handlers/gestures/nativeGesture'
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
> 71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:65
"export 'PanGestureType' (reexported as 'PanGesture') was not found in './handlers/gestures/panGesture'
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
> 65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:68
"export 'PinchGestureType' (reexported as 'PinchGesture') was not found in './handlers/gestures/pinchGesture'
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
> 68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'RaceGestureType' (reexported as 'RaceGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:69
"export 'RotationGestureType' (reexported as 'RotationGesture') was not found in './handlers/gestures/rotationGesture'
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
> 69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'SimultaneousGestureType' (reexported as 'SimultaneousGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:64
"export 'TapGestureType' (reexported as 'TapGesture') was not found in './handlers/gestures/tapGesture'
  62 | export { GestureDetector } from './handlers/gestures/GestureDetector';
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
> 64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
Web Bundling complete 3722ms
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:66
"export 'FlingGestureType' (reexported as 'FlingGesture') was not found in './handlers/gestures/flingGesture'
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
> 66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:70
"export 'ForceTouchGestureType' (reexported as 'ForceTouchGesture') was not found in './handlers/gestures/forceTouchGesture'
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
> 70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
./node_modules/react-native-gesture-handler/lib/module/index.js:79
"export 'GestureStateManagerType' (reexported as 'GestureStateManager') was not found in './handlers/gestures/gestureStateManager'
  77 |   ExclusiveGestureType as ExclusiveGesture,
  78 | } from './handlers/gestures/gestureComposition';
> 79 | export { GestureStateManagerType as GestureStateManager } from './handlers/gestures/gestureStateManager';
  80 | export { NativeViewGestureHandler } from './handlers/NativeViewGestureHandler';
  81 | export type {
  82 |   RawButtonProps,
./node_modules/react-native-gesture-handler/lib/module/index.js:67
"export 'LongPressGestureType' (reexported as 'LongPressGesture') was not found in './handlers/gestures/longPressGesture'
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
> 67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:72
"export 'ManualGestureType' (reexported as 'ManualGesture') was not found in './handlers/gestures/manualGesture'
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
> 72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:71
"export 'NativeGestureType' (reexported as 'NativeGesture') was not found in './handlers/gestures/nativeGesture'
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
> 71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
  73 | export {
  74 |   ComposedGestureType as ComposedGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:65
"export 'PanGestureType' (reexported as 'PanGesture') was not found in './handlers/gestures/panGesture'
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
  64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
> 65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:68
"export 'PinchGestureType' (reexported as 'PinchGesture') was not found in './handlers/gestures/pinchGesture'
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
> 68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
  69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'RaceGestureType' (reexported as 'RaceGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:69
"export 'RotationGestureType' (reexported as 'RotationGesture') was not found in './handlers/gestures/rotationGesture'
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
  68 | export { PinchGestureType as PinchGesture } from './handlers/gestures/pinchGesture';
> 69 | export { RotationGestureType as RotationGesture } from './handlers/gestures/rotationGesture';
  70 | export { ForceTouchGestureType as ForceTouchGesture } from './handlers/gestures/forceTouchGesture';
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'SimultaneousGestureType' (reexported as 'SimultaneousGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:64
"export 'TapGestureType' (reexported as 'TapGesture') was not found in './handlers/gestures/tapGesture'
  62 | export { GestureDetector } from './handlers/gestures/GestureDetector';
  63 | export { GestureObjects as Gesture } from './handlers/gestures/gestureObjects';
> 64 | export { TapGestureType as TapGesture } from './handlers/gestures/tapGesture';
  65 | export { PanGestureType as PanGesture } from './handlers/gestures/panGesture';
  66 | export { FlingGestureType as FlingGesture } from './handlers/gestures/flingGesture';
  67 | export { LongPressGestureType as LongPressGesture } from './handlers/gestures/longPressGesture';
```
Seems to not break the app.

**Comment by YZahringer** [comment]
fixed by #1791?

**Comment by ishikawa** [comment]
https://github.com/software-mansion/react-native-gesture-handler/issues/1786#issuecomment-1004899649

>fixed by #1791?

In our project, after installing the commit https://github.com/software-mansion/react-native-gesture-handler/commit/62e9eb66bced3b4c55042399d761baee7d961140, warnings were gone. So this issue should be fixed in the next release.

**Comment by danielkv** [comment]
I tried to install the latest version. the problem was not solved yet.

**Comment by gpkamp** [comment]
I installed version 2.1.1 and the problem is not solved yet for me either.

**Comment by Maker-Mark** [comment]
> I installed version 2.1.1 and the problem is not solved yet for me either.

If you install the commit that fixes it, it works.
ie
`		"react-native-gesture-handler": "https://github.com/software-mansion/react-native-gesture-handler#62e9eb66bced3b4c55042399d761baee7d961140",
`

**Comment by ishikawa** [comment]
Yeah, v2.1.1 doesn't contain https://github.com/software-mansion/react-native-gesture-handler/pull/1791, so you have to install the library from GitHub directly to resolve this issue. But I'm waiting for a new release because the build process in EAS build (Expo) was failed when I installed from GitHub https://github.com/software-mansion/react-native-gesture-handler/commit/62e9eb66bced3b4c55042399d761baee7d961140.

```
npm ERR! prepareGitDep > react-native-gesture-handler@2.1.0 prepare /Users/expo/.npm/_cacache/tmp/git-clone-0c99076e
[stderr] npm ERR! prepareGitDep > bob build
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep ℹ Building target commonjs
[stderr] npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/commonjs
[stderr] npm ERR! prepareGitDep ℹ Compiling 74 files in src with babel
[stderr] npm ERR! prepareGitDep ✔ Wrote files to lib/commonjs
[stderr] npm ERR! prepareGitDep ℹ Building target module
[stderr] npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/module
[stderr] npm ERR! prepareGitDep ℹ Compiling 74 files in src with babel
[stderr] npm ERR! prepareGitDep ✔ Wrote files to lib/module
[stderr] npm ERR! prepareGitDep ℹ Building target typescript
[stderr] npm ERR! prepareGitDep ℹ Cleaning up previous build at lib/typescript
[stderr] npm ERR! prepareGitDep ℹ Generating type definitions with tsc
[stderr] npm ERR! prepareGitDep src/web/utils.ts:23:37 - error TS2769: No overload matches this call.
[stderr] npm ERR! prepareGitDep       Type 'boolean' is not assignable to type 'number'.
[stderr] npm ERR! prepareGitDep   Overload 1 of 2, '(handler: () => void, timeout: number): number', gave the following error.
[stderr] npm ERR! prepareGitDep     Argument of type 'number | true' is not assignable to parameter of type 'number'.
[stderr] npm ERR! prepareGitDep   Overload 2 of 2, '(handler: () => void, timeout?: number | undefined): number', gave the following error.
[stderr] npm ERR! prepareGitDep     Argument of type 'number | true' is not assignable to parameter of type 'number | undefined'.
[stderr] npm ERR! prepareGitDep       Type 'true' is not assignable to type 'number | undefined'.
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep 23   return setTimeout(() => method(), interval);
[stderr] npm ERR! prepareGitDep                                        ~~~~~~~~
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep Found 1 error.
[stderr] npm ERR! prepareGitDep 
[stderr] npm ERR! prepareGitDep ✖ Failed to build definition files.
```

**Comment by Maker-Mark** [comment]
> [62e9eb6](https://github.com/software-mansion/react-native-gesture-handler/commit/62e9eb66bced3b4c55042399d761baee7d961140).

I'm using 62e9eb6. and not having an issue with EAS. Check your code and cache. It could be something else.

**Comment by Jonatthu** [comment]
> I can confirm this also still happening on web on latest versions

**Comment by indiejoseph** [comment]
+1 happening on web

**Comment by j-piasecki** [comment]
Hi! The just released GH 2.2.0 includes https://github.com/software-mansion/react-native-gesture-handler/pull/1791 which fixes this issue.

**Comment by danielkv** [comment]
> Hi! The just released GH 2.2.0 includes https://github.com/software-mansion/react-native-gesture-handler/pull/1791 which fixes this issue.

I'm going to try this today!

**Comment by danielkv** [comment]
I just tried here. It really solves the warning problems, BUT the Expo doesn't support the version 2.2.0 yet. It return another error message from Expo this time. I know that it's probably little changes and it'll not affect the core.

I'm gonna use it on staging to test it. If something goes wrong I'll leave a comment here.

**Comment by CarlosHdez** [comment]
> I just tried here. It really solves the warning problems, BUT the Expo doesn't support the version 2.2.0 yet. It return another error message from Expo this time. I know it's probably little changes and it'll not affect the core.
> 
> I'm gonna use it on staging to test it. If something goes wrong I'll leave a comment here.

Any updates on this? I did try version 2.2.0 with expo 44, the warnings disappear but now I get one in the iOS build saying that I might be using an old API

**Comment by danielkv** [comment]
> > I just tried here. It really solves the warning problems, BUT the Expo doesn't support the version 2.2.0 yet. It return another error message from Expo this time. I know it's probably little changes and it'll not affect the core.
> > I'm gonna use it on staging to test it. If something goes wrong I'll leave a comment here.
> 
> Any updates on this? I did try version 2.2.0 with expo 44, the warnings disappear but now I get one in the iOS build saying that I might be using an old API

I received this message, but I'm not sure why this happened nor how to fix it (the message). I'm using for 2 weeks the 2.2.0 with no errors, only the warnings.

**Comment by CarlosHdez** [comment]
Great, thanks.
I did some digging and it might be because I'm using `react-navigation` and the latest version seems to still be using stuff from old `react-native-gesture-handler` but also wasn't able to find any issues other than the warning 🤷‍♂️
