### ISSUE TITLE
Nested Touchables activate parent Touchable and break Flexbox

### ISSUE THREAD

**Issue by alexco2** [software-mansion/react-native-gesture-handler#1824]
## Description

1. When nesting one `TouchableOpacity` inside another and pressing it, the parent `TouchableOpacity` is activated as well. [Android]
2. `Flexbox` `flex` seems to be broken with nested `TouchableOpacity` [Android, IOS]
3. When wrapping the nested `TouchableOpacity` inside a `View` with `flex:1`, the `TouchableOpacity` disappears [Android, IOS] (when adding a padding, the `TouchableOpacity` seems to appear from the top (see snack)??)

## Steps To Reproduce

See Snack

### Expected behavior
The rngh `TouchableOpacity` should behave like the RN one as seen in the snack.

### Actual behavior
Flexbox and pressbehavior is broken

## Snack or minimal code example
https://snack.expo.dev/@expoco2/bugs-in-rngh

## Package versions

expo: sdk 43.0.0

**Comment by j-piasecki** [comment]
Hi! Thanks for the report and for the snack. The first issue should be fixed by Gesture Handler 2 which is included in Expo 44.

As for the other two, unfortunately GH Touchables are not a drop-in replacement for the React Native ones. The main difference is that they render one more view which also needs to be styled. You can do this using `containerStyles` prop.
In this case I believe that adding `containerStyle={{ flex: 1 }}` to both yellow Touchables from GH will make it look as intended.

**Comment by alexco2** [comment]
Thank you for your quick answer! I will upgrade rngh in my vanilla rn project and check if this solves the issue. If so, I´ll close the issue.
Also, thank you for your explanation regarding flexbox! :)

**Comment by alexco2** [comment]
Using react-native-gesture-handler 2.1.1 the issue with pressing the parent touchable still persists.

**Comment by j-piasecki** [comment]
Hmm, that's weird. I tried it on the code from the snack and it's working for me. Could you prepare a repository with a reproduction of this?

**Comment by alexco2** [comment]
I´ll try to provide something as soon as i find some time. Hopefully this week.

**Comment by j-piasecki** [comment]
Hi! Any updates on this?

**Comment by alexco2** [comment]
Hello @j-piasecki, sorry for letting you wait so long. I'm trying to create a repo in a vanilla RN project with RNGH 2.3.0 with the code from the snack but somehow it is not working (buttons are not clickable) and I get the the error 
`[react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!`
Do you have an idea what the problem could be? As soon as I can get the repo working I will test if the issue persists with the new RNGH version.

**Comment by j-piasecki** [comment]
If you're using vanilla RN, don't forget to wrap the application component with `GestureHandlerRootView` (and keep in mind that it will behave just as a `View` would, meaning you might want to add `style={{ flex: 1 }}` to it to make it fill the screen).
As for the message you mentioned, it's nothing to worry about. It was supposed to nudge people to migrate to the new API.

**Comment by alexco2** [comment]
@j-piasecki 
Great, thank you. I was not able to replicate it and will now work on implementing version 2.3.0 in my production app. If I come across the bug again, I will reopen this issue. Until then, this issue is closed. Thank you for your support! :)
