### ISSUE TITLE
DrawerLayout broken on RN 0.70

### ISSUE THREAD

**Issue by lightrow** [software-mansion/react-native-gesture-handler#2208]
### Description

Updated RN from 0.68 to 0.70 - DrawerLayout reappears right after closing and stays on the screen until you try to pull it out again

### Steps to reproduce

1.  Open DrawerLayout
2. Close DrawerLayout
3. Drawer pops back after closing and doesn't go away

### Snack or a link to a repository

--

### Gesture Handler version

2.6.0

### React Native version

0.70.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by renchap** [comment]
I can confirm this on my app, it happens with both iOS and Android.

**Comment by siderakis** [comment]
https://github.com/software-mansion/react-native-gesture-handler/blob/main/example/src/new_api/betterHorizontalDrawer/BetterHorizonatalDrawer.tsx is working for RN 70 although the touch interaction is slightly different (at-least for draw type "front"). The border edge jumps to where the finger is which can be quite abrupt when it in the middle of the draw.

**Comment by renchap** [comment]
As mentioned in https://github.com/facebook/react-native/issues/34665, using `<DrawerLayout useNativeAnimations={false} />` fixes the issue.

This is a workaround until the real `Animated` bug is fixed, I tested it both on Android and iOS.

**Comment by j-piasecki** [comment]
Fixed in https://github.com/facebook/react-native/pull/34927.

**Comment by atheck** [comment]
I still have that issue with react-native 0.70.4 and react-native-gesture-handler 2.8.0 using the old architecture.

Setting `useNativeAnimations` to `false`  fixes the issue, but the animations are stuttering. Am I missing something?

**Comment by Nova41** [comment]
Still getting the bug in 0.70.4.

**Comment by mikehardy** [comment]
Desire aside, the only workaround appears to be as described: disable native animations
Alternatively, the fix [commit link](https://github.com/facebook/react-native/commit/2f58e520061a31ab90f7bbeef59e2bf723605106) shows it is on the react-native 0.71 stable branch, which is on rc3 at the moment), so if you desire native animations strongly enough, update to react-native 0.71.0-rc.3 to get the solution, or wait until 0.71.0 is released as stable then upgrade

**Comment by kelset** [comment]
@mikehardy that commit has been cherry picked in 0.70.3: https://github.com/facebook/react-native/releases/tag/v0.70.3

**Comment by mikehardy** [comment]
Oh! That changes things if I misread that, sorry everyone. So this should be fixed but is not? 🤔

**Comment by kelset** [comment]
it should, yeah

**Comment by j-piasecki** [comment]
It seems like the problem still persists when the animation gets interrupted by another one. I've added a comment with an explanation and repro in the issue in the React Native repo.

**Comment by hotaryuzaki** [comment]
I can confirm this issue still exists in react-native-gesture-handler 2.8.0
if i open the drawer and quickly close it, the drawer view will reappear. and then I cannot close it again.
it looks like that open animation process still running and change the state.
useNativeAnimations set to false solve the issue.

so the problem is from RN core?

**Comment by j-piasecki** [comment]
@hotaryuzaki Yes, the problem is from RN core, but AFAIK the 0.71 doesn't have that issue so upgrading may solve the problem.

**Comment by segicm** [comment]
Any updates on this? The problem persists for the past 6 months...

**Comment by lightrow** [comment]
we are still using this
https://github.com/software-mansion/react-native-gesture-handler/blob/main/example/src/new_api/betterHorizontalDrawer/BetterHorizonatalDrawer.tsx
with some tweaks to make drawerType={'slide'} work at cost of others that we don't need

**Comment by Adr1anPopescu** [comment]
Any update here?

**Comment by dinhthi147** [comment]
Any updates on this? I still have to disable useNativeAnimations

**Comment by traxx10** [comment]
Same issue here as well

**Comment by linxianxi** [comment]
same

**Comment by shubhamguptadream11** [comment]
Same issue here as well in `RN 0.72.4 `with` react-native-gesture-handler": "2.7.1`.
By disabling native animations it worked but I don't want to do that.

**Comment by linxianxi** [comment]
try https://reactnavigation.org/docs/drawer-layout/ I used this now, it works fine.

**Comment by latekvo** [comment]
Hi, the `DrawerLayout` component of `RNGH` is now deprecated by `ReanimatedDrawerLayout`.
This bug should be fixed by the new `ReanimatedDrawerLayout` component.
