### ISSUE TITLE
Error ParagraphShadowNode.h file not found

### ISSUE THREAD

**Issue by featlast** [software-mansion/react-native-gesture-handler#3385]
### Description

Showing All Errors Only
CompileC /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/RNGestureHandlerModule.o /Users/jose/Desktop/projects/Chile/newFileApp/FCliente/node_modules/react-native-gesture-handler/apple/RNGestureHandlerModule.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNGestureHandler' from project 'Pods')
    cd /Users/jose/Desktop/projects/Chile/newFileApp/FCliente/ios/Pods
    
    Using response file: /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp
    
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/jose/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.2-22C146-07b28473f605e47e75261259d3ef3b5a.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/jose/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Index.noindex/DataStore -Wno-comma -Wno-shorten-64-to-32 @/Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DRCT_NEW_ARCH_ENABLED\=1 -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -include /Users/jose/Desktop/projects/Chile/newFileApp/FCliente/ios/Pods/Target\ Support\ Files/RNGestureHandler/RNGestureHandler-prefix.pch -MMD -MT dependencies -MF /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/RNGestureHandlerModule.d --serialize-diagnostics /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/RNGestureHandlerModule.dia -c /Users/jose/Desktop/projects/Chile/newFileApp/FCliente/node_modules/react-native-gesture-handler/apple/RNGestureHandlerModule.mm -o /Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/RNGestureHandlerModule.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/RNGestureHandler.build/Objects-normal/arm64/RNGestureHandlerModule.o

/Users/jose/Desktop/projects/Chile/newFileApp/FCliente/node_modules/react-native-gesture-handler/apple/RNGestureHandlerModule.mm:17:9: fatal error: 'react/renderer/components/text/ParagraphShadowNode.h' file not found
   17 | #import <react/renderer/components/text/ParagraphShadowNode.h>
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jose/Desktop/projects/Chile/newFileApp/FCliente/node_modules/react-native-gesture-handler/apple/RNGestureHandlerModule.mm:17:9: note: did not find header 'renderer/components/text/ParagraphShadowNode.h' in framework 'react' (loaded from '/Users/jose/Library/Developer/Xcode/DerivedData/FCliente-dqwkdzhglctoykctinygewyrwvpm/Build/Products/Debug-iphonesimulator/React-Core')
1 error generated.

/Users/jose/Desktop/projects/Chile/newFileApp/FCliente/node_modules/react-native-gesture-handler/apple/RNGestureHandlerModule.mm:17:9: 'react/renderer/components/text/ParagraphShadowNode.h' file not found

### Steps to reproduce

none

### Snack or a link to a repository

none

### Gesture Handler version

2.23.0

### React Native version

0.77

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

### Steps to reproduce

none

### Snack or a link to a repository

none

### Gesture Handler version

2.23.0

### React Native version

0.77

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by ROG3R-DEV** [comment]
Same problem here. The problem happens on react-native equal or greater than 0.76.6.

![Image](https://github.com/user-attachments/assets/ef290cde-39f9-4af5-ac31-b903dea14267)

**Comment by AftabUfaq** [comment]
same issue

**Comment by m-bert** [comment]
Hi @featlast! I've just built fresh React Native app on 0.77, added Gesture Handler 2.23.0 and replaced `Text` from `react-native` with `Text` from `react-native-gesture-handler`. Everything works fine. 

I see that you error logs point into `DerivedData`, have you tried cleaning those? Have you cleaned caches and performed clean build?

**Comment by m-bert** [comment]
@ROG3R-DEV I've done the same thing with 0.76.6, works fine on my end.

**Comment by 0xDing** [comment]
> Hi [@featlast](https://github.com/featlast)! I've just built fresh React Native app on 0.77, added Gesture Handler 2.23.0 and replaced `Text` from `react-native` with `Text` from `react-native-gesture-handler`. Everything works fine.
> 
> I see that you error logs point into `DerivedData`, have you tried cleaning those? Have you cleaned caches and performed clean build?


This issue seems to be related to `use_frameworks! :linkage => :static` in the Podfile.

**Comment by m-bert** [comment]
> This issue seems to be related to use_frameworks! :linkage => :static in the Podfile.

I'm not sure why static linking would break this. I've changed it in `Podfile` in fresh app and it still runs fine.

**Comment by featlast** [comment]
> Hola[@featlast](https://github.com/featlast)Acabo de crear una nueva aplicación React Native en la versión 0.77, agregué Gesture Handler 2.23.0 y reemplacé `Text`from `react-native`por `Text`from `react-native-gesture-handler`. Todo funciona bien.
> 
> Veo que los registros de errores apuntan a `DerivedData`, ¿ha intentado limpiarlos? ¿Ha limpiado los cachés y ha realizado una compilación limpia?

Hello @m-bert , greetings, that's right, I cleaned the build and the XCODE DerivedData and the error persisted.

**Comment by m-bert** [comment]
In that case, please provide a reproduction that we can look at 😅

**Comment by gideon-uiby** [comment]
Just include it at the top of the file like this 
```
#include "ParagraphShadowNode.h"
```

and remove the import

**Comment by gideon-uiby** [comment]
can we get a quick PR and release for this fix? @m-bert

**Comment by 0xDing** [comment]
> > This issue seems to be related to use_frameworks! :linkage => :static in the Podfile.
> 
> I'm not sure why static linking would break this. I've changed it in `Podfile` in fresh app and it still runs fine.

Apologies, I don't have the time to create a standalone minimal reproduction at the moment.  However, I can confirm that the following modification to the Podfile—adding additional `header_search_paths`—helped me resolve the issue:

```ruby
require "json"

is_gh_example_app = ENV["GH_EXAMPLE_APP_NAME"] != nil

compilation_metadata_dir = "CompilationDatabase"
compilation_metadata_generation_flag = is_gh_example_app ?  '-gen-cdb-fragment-path ' + compilation_metadata_dir : ''

header_search_paths = []

if ENV['USE_FRAMEWORKS']
header_search_paths.concat([
'"${PODS_CONFIGURATION_BUILD_DIR}/React-FabricComponents/React_FabricComponents.framework/Headers"',
'"${PODS_CONFIGURATION_BUILD_DIR}/React-FabricComponents/React_FabricComponents.framework/Headers/react/renderer/textlayoutmanager/platform/ios"',
])
end

Pod::Spec. new do |s|
# NPM package specification
package = JSON.parse(File.read(File.join(File.dirname(__FILE__), "package.json")))

s.name         = "RNGestureHandler"
s.version      = package["version"]
s.summary      = package["description"]
s.homepage     = "https://github.com/software-mansion/react-native-gesture-handler"
s.license      = "MIT"
s.author       = { package["author"]["name"] => package["author"]["email"] }
s.source       = { :git => "https://github.com/software-mansion/react-native-gesture-handler", :tag => "#{s. version}" }
s.source_files = "apple/**/*.{h,m,mm}"
s.requires_arc = true
s.platforms       = { ios: '11.0', tvos: '11.0', osx: '10.15', visionos: '1.0' }
s.xcconfig = {
"OTHER_CFLAGS" => "$(inherited)  " + compilation_metadata_generation_flag,
'HEADER_SEARCH_PATHS' => header_search_paths. join(' ')
}

if defined?(install_modules_dependencies()) != nil
install_modules_dependencies(s);
else
s.dependency "React-Core"
end
end
```

I suspect the issue is similar to a past one I encountered with Expo, which is discussed here: https://github.com/expo/expo/issues/32142#issuecomment-2565075486

**Comment by featlast** [comment]
![Image](https://github.com/user-attachments/assets/f192ad99-be6f-4320-be9a-d2522d0e9b59)

brother, this is the error, if I install version 2.23.0, then I decided to install version 2.22.0, and it solves my case

**Comment by m-bert** [comment]
Could you please check if #3338 fixes this?

**Comment by gideon-uiby** [comment]
@featlast this weirdly fixes the error, but do we know what the root cause is?

<img width="358" alt="Image" src="https://github.com/user-attachments/assets/bd565cdc-825d-48fa-bcbe-c9bc6bea0692" />

**Comment by m-bert** [comment]
Sorry, I made a mistake in my previous comment as those numbers are similar, I meant #3388 

@featlast, @0xDing, @gideon-uiby, could you please check that PR?

**Comment by 0xDing** [comment]
> Sorry, I made a mistake in my previous comment as those numbers are similar, I meant [#3388](https://github.com/software-mansion/react-native-gesture-handler/pull/3388)
> 
> [@featlast](https://github.com/featlast), [@0xDing](https://github.com/0xDing), [@gideon-uiby](https://github.com/gideon-uiby), could you please check that PR?

It's work for me.

React Native: 0.77

**Comment by ROG3R-DEV** [comment]
This fixed it for me

`rm -rf ios/build ios/Pods ios/Podfile.lock`

`cd ios && RCT_NEW_ARCH_ENABLED=0 pod install`

react-native 0.77.0
react-native-gesture-handler 2.23.0

**Comment by drumsSandoval** [comment]
`bundle Install`

It's Worked For me uwu!

**Comment by marioecs** [comment]
Downgrading react-native-gesture-handler to 2.22.0 works well!!

In this [documentation](https://github.com/software-mansion/react-native-gesture-handler/blob/1f9f20bcb1725396160a28ad5e2d1f7485b9babb/README-Fabric.md) it is mentioned that the version must be 2.3.0, but the ParagraphShadowNode.h file not found error persists

**Comment by anudit** [comment]
Running into this too with 

- reactNativeTargetVersion: 0.76.7
- fabric_enabled: true
- linkage: static
- newArch: true

Downgrading to `2.22.0` fixed it for now.

**Comment by SurendraSp** [comment]
> Running into this too with
> 
> * reactNativeTargetVersion: 0.76.7
> * fabric_enabled: true
> * linkage: static
> * newArch: true
> 
> Downgrading to `2.22.0` fixed it for now.

Not working for me 😖

**Comment by koreanddinghwan** [comment]
i had same issue but solved.

before
> reactNativeTargetVersion: 0.76.7
> fabric_enabled: true
> linkage: static
> newArch: true
> gesturehandler v2.3

after
> reactNativeTargetVersion: 0.76.7
> fabric_enabled: true
> linkage: static
> newArch: true
> gesturehandler **v2.22.0**


The two files differs at:
https://github.com/software-mansion/react-native-gesture-handler/blob/2.22.0/apple/RNGestureHandlerModule.mm
https://github.com/software-mansion/react-native-gesture-handler/blob/2.23.0/apple/RNGestureHandlerModule.mm

show that in version 2.23.0, the following lines were added:

> #import <react/renderer/components/text/ParagraphShadowNode.h>
> #import <react/renderer/components/text/TextShadowNode.h>

and using version 2.22.0, which does not have this header, allowed the build to succeed.

**Comment by SurendraSp** [comment]
Thanks @koreanddinghwan for that file links.
After that i checked inside node modules which i have installed and i found it's `2.23.0` instead of `2.22.0` then i found it happen because of `^` in version.
Just FYI: If you downgrading version `"react-native-gesture-handler": "^2.22.0"` make to remove `^` from version. 😵‍💫

**Comment by popocreator** [comment]
Same Issue

**Comment by brianaderer** [comment]
Same issue. Blocked on building. started on RN 76.2. Didn't work with v 2.22 or 2.23. Upgrated to RN 77.0. Still doesn't work with v 2.23

**Comment by tremblerz** [comment]
I wanted to use 2.23 because of the bug fixes so I manually applied the patch introduced in the above mentioned PR and it worked like a charm. If you, like me, can't wait for the PR to be merged, apply the following changes RNGestureHandler.podspec file inside the installed library folder in `node_modules` -

```
if ENV['USE_FRAMEWORKS'] != nil && ENV['RCT_NEW_ARCH_ENABLED'] == '1'
    add_dependency(s, "React-FabricComponents", :additional_framework_paths => [
      "react/renderer/textlayoutmanager/platform/ios",
      "react/renderer/components/textinput/platform/ios",
    ])
    add_dependency(s, "React-rendererconsistency")
  end
```

**Comment by m-bert** [comment]
Hi! I've done small change into PR, could you please check if it still works? #3388. If so, I'd like to merge it as soon as possible (cc @0xDing).

**Comment by shuvajitmaitra** [comment]
It's work for me:

yarn add react-native-gesture-handler@2.22.0

cd ios

pod install

**Comment by m-bert** [comment]
FYI, I've just released [2.23.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.23.1) that includes fix for this problem 😅

**Comment by m-bert** [comment]
Hi @faljabi! Have you tried _**Gesture Handler**_ from [this branch](https://github.com/software-mansion/react-native-gesture-handler/pull/3530)? I have not seen this error and everything was built correctly.

**Comment by joprice** [comment]
@m-bert I tried that branch with 0.80.0-rc.4 and I'm still getting the same missing header error.

**Comment by m-bert** [comment]
Thanks for checking that! [This commit](https://github.com/software-mansion/react-native-gesture-handler/pull/3530/commits/d0ab514eec1ac5a782690145b1cf0241c8be2768) should fix the issue 😅

**Comment by dhruvpaobs** [comment]
I upgraded from React Native 0.79.2 to 0.80 and got this error: 'react/renderer/components/text/ParagraphState.h' file not found. I think it's time to add support for React Native 0.80 in react-native-gesture-handler, since the latest version is now released. Requesting the maintainer to please review and merge these changes: @mbert/monorepo-80rc2.

![Image](https://github.com/user-attachments/assets/fef84b92-d872-476e-a295-b68bf6aa6d27)

**Comment by m-bert** [comment]
FYI, I've just released [2.26.0](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.26.0)
