### ISSUE TITLE
Pressable stops working

### ISSUE THREAD

**Issue by vendramini** [software-mansion/react-native-gesture-handler#3476]
### Description

This is a really weird behavior, I've been facing it from time to time eventually - only on Android on both real devices and simulators.

I have a big and complex project, and sometimes it just stops receiving clicks on `Pressable` component.

Today I put some debugging on `Pressable.tsx` and I've found that `isTouchPropagationAllowed.current` is always `false`. The main function is:
```typescript
const pressOutHandler = useCallback(
      (event: PressableEvent) => {
        console.log('pressOutHandler', isTouchPropagationAllowed.current)

        if (!isTouchPropagationAllowed.current) {
          hasPassedBoundsChecks.current = false;
          isPressCallbackEnabled.current = true;
          deferredEventPayload.current = null;

          if (longPressTimeoutRef.current) {
            clearTimeout(longPressTimeoutRef.current);
            longPressTimeoutRef.current = null;
          }

          if (pressDelayTimeoutRef.current) {
            clearTimeout(pressDelayTimeoutRef.current);
            pressDelayTimeoutRef.current = null;
          }

          return;
        }

        if (
          !hasPassedBoundsChecks.current ||
          event.nativeEvent.touches.length >
            event.nativeEvent.changedTouches.length
        ) {
          return;
        }

        if (unstable_pressDelay && pressDelayTimeoutRef.current !== null) {
          // When delay is preemptively finished by lifting touches,
          // we want to immediately activate it's effects - pressInHandler,
          // even though we are located at the pressOutHandler
          clearTimeout(pressDelayTimeoutRef.current);
          pressInHandler(event);
        }

        if (deferredEventPayload.current) {
          onPressIn?.(deferredEventPayload.current);
          deferredEventPayload.current = null;
        }

        onPressOut?.(event);

        if (isPressCallbackEnabled.current) {
          onPress?.(event);
        }

        if (longPressTimeoutRef.current) {
          clearTimeout(longPressTimeoutRef.current);
          longPressTimeoutRef.current = null;
        }

        console.log(4);

        isTouchPropagationAllowed.current = false;
        hasPassedBoundsChecks.current = false;
        isPressCallbackEnabled.current = true;
        setPressedState(false);
      },
      [onPress, onPressIn, onPressOut, pressInHandler, unstable_pressDelay]
    );
```
As being `false` its execution stops on the first condition, not firing `onPress`.

I couldn't reproduce it in a repro, but it is happening often on my project.

My `_layout.tsx`:
```typescript
return (
    <GestureHandlerRootView style={{flex: 1}}>
      <LoaderFullscreen>
        <trpc.Provider client={trpcClient} queryClient={queryClient}>
          <CustomConfirmationBottomSheetModalProvider>
            <CustomBottomSheetModalProvider>
              <ThemeProvider value={DefaultReactNavigationTheme}>
                <CustomQueryClientProvider>
                  <KeyboardProvider statusBarTranslucent>
                    <SafeAreaProvider initialMetrics={initialWindowMetrics}>
                      <AuthProvider>
                        <App />
                      </AuthProvider>
                    </SafeAreaProvider>
                  </KeyboardProvider>
                </CustomQueryClientProvider>
              </ThemeProvider>
            </CustomBottomSheetModalProvider>
          </CustomConfirmationBottomSheetModalProvider>
        </trpc.Provider>
      </LoaderFullscreen>
      {toastContent}
    </GestureHandlerRootView>
  );
```

As a temporary (I hope) solution, I'll have to use `<GestureDetector gesture={singleTap}>` on each clickable spot and handle it manually. That way it always works.

### Steps to reproduce

1. Just open my app and try clicking on some buttons. It doesn't happen all the time, but quite often.

### Snack or a link to a repository

I couldn't reproduce it.

### Gesture Handler version

2.25.0

### React Native version

0.77.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Moto g60

### Acknowledgements

Yes

**Comment by vendramini** [comment]
When this issue occur I usually change to `Pressable` from react-native. It turns out that it has already happened before with it (Pressable from RN), then I switched to RNGH. Now it started happening with it.

Sorry about not being able to reproduce it in an isolated project, but it is just not happening - but it does happen on my project.

Happy to debug together with you guys.

**Comment by latekvo** [comment]
Hey, could you please let me know if this issue also occurs on RNGH 2.24.0?
We've made some [changes](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) to pressOutHandler in RNGH 2.25.0 that could be the cause of this bug.

**Comment by iankberry** [comment]
I have also been having the issue occasionally since swapping out all of the RN Pressable components in my app with the RNGH version (using 2.25.0). It almost seems like a gesture is getting "stuck" as the Pressable sometimes stays in a pressed state (different background color). When the issue occurs I have to restart the entire app to get back into a good state. I use react-navigation and the RNGH FlatList component on most screens so that could certainly be related.

One thing that did seem to make a difference for me - I had a PressableWithoutFeedback component covering the entire screen to catch things like taps outside of a modal. Although it was disabled, after removing it I'm not experiencing the issue much anymore. Maybe unrelated but there seemed to be a correlation.

**Comment by vendramini** [comment]
@latekvo you right! On 2.24.0 it doesn't occur. However, it is not working my pressed style on 2.24.0 (it does work on 2.25.0):
```typescript
<Pressable style={styles.pressable} hitSlop={10} {...buttonProps}>
//stuff
</Pressable>

const stylesheet = createStyleSheet(({ colors }) => ({
  pressable: ({ pressed }: { pressed: boolean }) => ({
    opacity: pressed ? 0.5 : 1,
  }),
}));
```
It also feels more fluid and the touch seems to respond faster.

**Comment by latekvo** [comment]
@iankberry thanks for providing the video! Your issue seems most likely related to [this one](https://github.com/software-mansion/react-native-gesture-handler/pull/3350). 
I think there's a low chance it's related to the one reported by @vendramini, but I could be wrong.

Unfortunately, we haven't found any workarounds or fixes for this issue yet, but I'll keep you updated if we do find anything.

**Comment by iankberry** [comment]
@latekvo That's certainly possible, it seems to surface when paired with scrolling. I'll go ahead and subscribe to that issue then. I greatly appreciate you looking into this and your contribution to this fantastic library!

**Comment by shovel-kun** [comment]
Ah, I think the bug I'm facing is related to #3350

**Comment by Unuuuuu** [comment]
I have the same issue as well

**Comment by eetzuh** [comment]
I am using Expo 52 and React Native 0.77.1 and I have the same issue, but **only on development builds**. Release builds work without issues. If you must use react-native-gesture-handler buttons I suggest you try building a release variant and see if they work, otherwise I use regular react-native buttons when there is no need to use this library (for example, I found out that modals and bottom sheets work better with gesture handler buttons, and that is about it where they are beneficial). This inconsistency and mixing button libraries in one project very messy. I hope this gets fixed because Expo and React Native push the usage of this library, and many third party libraries rely on it, so we don't really have the option to not use it.

**Comment by hwildwood** [comment]
I'm using Expo 52, React Native 0.76 and RNGH 2.25.  I'm experiencing the same issue.  Pressable doesn't seam to work inside lists.

**Comment by SumitR9910** [comment]
it does works in v2.23.0 but after the list has stopped scrolling there is a few milliseconds delay before the pressable registers user click, thus many times resulting in having to click the same pressable two times so it can execute the onPress callback

**Comment by atambo** [comment]
I’m also experiencing this with expo 52, react native 0.77, and all the versions of gesture handler. Pressable inside of a Flatlist stop working randomly on android. I think it is maybe related to when I use scrollTo to move through the Flatlist?

**Comment by mattlennon3** [comment]
Also experiencing this. The `Pressable` component works great, apart from when it's within `BottomSheetModal` from `@gorhom/bottom-sheet` (version `4.6.4`). Then it is really unresponsive.

Using the inbuilt `react-native` `Pressable` component fixes this in the meantime.

**Comment by vendramini** [comment]
It can be a misunderstanding of mine, specially because I have no idea how RN works in practice (I know the theory, but not the implementation challenges), but doesn't it sound worry (sad) that the core library `react-native` itself can't make a simple functional button (a button!) that fits all needs and scenarios? They have to rely on some third-party library, that also face the same issue.

I'm not complaining nor judging you guys, serious, don't take that way. I've been using RN and RNGH for years. My comment here is more like "we are building products on top of it. Isn't it dangerous? How can we push a technology that faces simple problems?". Again, "simple problems" from the point of view of those who are consuming the API. Maybe it can be really hard to make it work with issue.

Does anyone know any articles or youtube video that go deep and show the challenges and issue of RN and why these kind of thing happen so often?

**Comment by qwalker8408** [comment]
I sometimes think it's a react modal or modal "thing" that wasn't closed properly but you navigate away from where that modal was, perhaps programmatically. It results in some sort of freeze on new screens and there's simply no way to recover from it othan than to restart the app. From what I see in my app it seems to still feel like it's operating, as no drops on fps or performance has occured but yet it's still "frozen" and unresponsive. I do agree with the sentiment of it occuring in scroll views of any sort.

**Comment by KCherkalov** [comment]
I have same issue in project for android release builds. Its happen when I upgraded deps: react-native: 0.73.9 -> 78.2, react-native-gesture-handler: 2.19.0 -> 2.25.0

**Comment by baylesa-dev** [comment]
Here is a repository to reproduce the issue : https://github.com/baylesa-dev/PressableIssue

It does not work in a rngh FlatList, but works well outside of the list

```tsx
function App(): React.JSX.Element {
    const renderItem = useCallback(
        ({item}: ListRenderItemInfo<(typeof fakeUsers)[0]>) => (
            <Pressable
                style={styles.listItem}
                onPress={() => console.log('Item Pressed!')}> // its does not work
                <Text>{item.name}</Text>
            </Pressable>
        ),
        [],
    );

    return (
        <GestureHandlerRootView>
            <View style={styles.container}>
                <Pressable
                    style={styles.card}
                    onPress={() => console.log('Card Pressed!')}> // it works !
                    <View>
                        <Text style={styles.text}>Hello World</Text>
                    </View>
                </Pressable>

                <FlatList
                    style={styles.list}
                    data={fakeUsers}
                    renderItem={renderItem}
                    disableScrollViewPanResponder
                />
            </View>
        </GestureHandlerRootView>
    );
}
```

**Comment by a-klotz-p8** [comment]
Also facing some `Pressables` barely even being responsive. This occured after upgrading from **2.24 to 2.25**. Seems like the issue was introduced there. For me this issue mainly occurs on `iOS` and creating a release build did not fix this for me the issue just occurs a bit less often.

**Comment by a-klotz-p8** [comment]
The issue on iOS seems to be cause by this change: #3295. Maybe someone can investigate further from here.

**Comment by techied** [comment]
Would the maintainers be interested in sponsorship to fix these issues (on iOS and Android)? This is a really big problem for us and it's been affecting our app for quite some time now.

**Comment by atambo** [comment]
I believe this is a minimal reproduction: https://github.com/baylesa-dev/PressableIssue

I would also be willing to monetarily sponsor a fix to this issue.

**Comment by gigobyte** [comment]
Reverting the changes in this PR https://github.com/software-mansion/react-native-gesture-handler/pull/3295 using patch-package fixed the issue for me.

**Comment by a-klotz-p8** [comment]
> Reverting the changes in this PR [#3295](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) using patch-package fixed the issue for me.

That's also what I observed

**Comment by fsvapat** [comment]
> Reverting the changes in this PR [#3295](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) using patch-package fixed the issue for me.

Same, but it brings back the nested Pressables issue.

**Comment by pierroo** [comment]
> Reverting the changes in this PR [#3295](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) using patch-package fixed the issue for me.

can you please share your patch-package?
this issue is quite frustrating, and I prefer the nested pressable issue over this one :)

**Comment by gigobyte** [comment]
> > Reverting the changes in this PR [#3295](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) using patch-package fixed the issue for me.
> 
> can you please share your patch-package? this issue is quite frustrating, and I prefer the nested pressable issue over this one :)

~~I don't think there's a need, upgrading to 2.26.0 fixed the issue for me.~~ I lied, I just had stale node_modules 😓

**Comment by pierroo** [comment]
> > > Reverting the changes in this PR [#3295](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) using patch-package fixed the issue for me.
> > 
> > 
> > can you please share your patch-package? this issue is quite frustrating, and I prefer the nested pressable issue over this one :)
> 
> I don't think there's a need, upgrading to 2.26.0 fixed the issue for me.

I'm using 2.26.0 as well, and yet I still sometimes face the pressable no longer working. :/

**Comment by techied** [comment]
The lack of attention for a completely breaking issue like this one on such a core library used by almost every React Native app is frustrating to see.

We don't have the time to contribute to a fix but we are willing to start a bounty of $500 for a pull request or patch to fix the issues on Android under React Native 0.77, old architecture.

**Comment by latekvo** [comment]
Please let me know if #3571 works on your setups.

Tested it on the repro sent by @baylesa-dev and it now seems to be working well.
Also tested with our example app on every supported platform, and haven't found any new issues.

(c.c. @vendramini, @techied)

**Comment by tannerbaum** [comment]
> Please let me know if [#3571](https://github.com/software-mansion/react-native-gesture-handler/pull/3571) works on your setups.
> 
> Tested it on the repro sent by [@baylesa-dev](https://github.com/baylesa-dev) and it now seems to be working well. Also tested with our example app on every supported platform, and haven't found any new issues.
> 
> (c.c. [@vendramini](https://github.com/vendramini), [@techied](https://github.com/techied))

@latekvo Is there an easy way to test that branch in our projects? I tried setting the version to 

`"react-native-gesture-handler": "github:software-mansion/react-native-gesture-handler#@latekvo/rewrite-pressable-to-state-machine",` 

in my pnpm project's package.json but I end up getting a metro error. 

My issue I have run into with existing versions of Gesture Handler is when my Pressable is a child of a React Native Primitives `Slot.Pressable`. I can't say I know much about the library. Maybe that's one of the issues with passing the ref along mentioned in the PR? 

Oh looks like its also with ExpoRouter's Link using `asChild`

**Comment by m-bert** [comment]
@tannerbaum I'm not sure how adding directly from branches works in `pnpm`, but you can add `.patch` to pull request URL and then apply this [patch](https://patch-diff.githubusercontent.com/raw/software-mansion/react-native-gesture-handler/pull/3571.patch) with `patch-package`

**Comment by tannerbaum** [comment]
> [@tannerbaum](https://github.com/tannerbaum) I'm not sure how adding directly from branches works in `pnpm`, but you can add `.patch` to pull request URL and then apply this [patch](https://patch-diff.githubusercontent.com/raw/software-mansion/react-native-gesture-handler/pull/3571.patch) with `patch-package`

Thanks, patch-package doesn't seem to work well with pnpm but you set me down the right path. Take everything with a grain of salt coming from a react-native newbie – and because for whatever reason I had to add the ../utils.ts file inside the components directory even though that isn't part of the PR which is fishy – but I found that with the patch: 

- It fixed the issue I had with ExpoRouter Link which wasn't present in 2.24 but in 2.25 
- It did not fix the React Native Primitive issue, which I will share a snippet of here: 

```tsx

// Button call
<DropdownMenu>
    <DropdownMenuTrigger asChild>
        {/* Our custom button component, which is GH's Pressable and children */}
           <Button title="Upload Your Own" rounded="slight" type="outline" /> 
      </DropdownMenuTrigger>
```
```tsx
// DropdownMenu.tsx
import * as DropdownMenuPrimitive from "@rn-primitives/dropdown-menu";
// ...

// A "ReactForwardRefExoticComponent" that omits ref from Native's PressableProps and adds an asChild prop
const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;

```

It's possible that these two libraries just aren't meant to interact, which is fine because I found I can just pass a prop to my Button component where I conditionally render either Pressable from RN or RNGH. I just wanted to share in case it somehow helped the team during this refactor.

**Comment by latekvo** [comment]
@tannerbaum  Does this ref type conflict occur in 2.25 too? Or just after applying this patch?
I just pushed a small fix to the type of the `ref`, I hope it'll help with your case.

**Comment by tannerbaum** [comment]
> [@tannerbaum](https://github.com/tannerbaum) Does this ref type conflict occur in 2.25 too? Or just after applying this patch? I just pushed a small fix to the type of the `ref`, I hope it'll help with your case.

It didn't fix the main issue, and actually regressed your fix for the Expo Link parent case that I had. Since when I patched it I also through in a console log, I could see that with that ref addition I wasn't making it to 
```
      if (isOnPressAllowed.current) {
        onPress?.(event);
      }
``` 

in `Pressable.tsx`, but after removing it again I did make it there. And also in the case of the RN Primitive bug.

As one final thing to share, I went up and found the source code for the RN Primitive component (I don't think its too widely used in general, not sure it should hold up all your great work).

```tsx
const Trigger = React.forwardRef<TriggerRef, TriggerProps>(
  ({ asChild, onPress: onPressProp, disabled = false, ...props }, ref) => {
    const { open, onOpenChange, setTriggerPosition } = useRootContext();

    const augmentedRef = useAugmentedRef({
      ref,
      methods: {
        open: () => {
          onOpenChange(true);
          augmentedRef.current?.measure((_x, _y, width, height, pageX, pageY) => {
            setTriggerPosition({ width, pageX, pageY: pageY, height });
          });
        },
        close: () => {
          setTriggerPosition(null);
          onOpenChange(false);
        },
      },
    });

    function onPress(ev: GestureResponderEvent) {
      if (disabled) return;
      augmentedRef.current?.measure((_x, _y, width, height, pageX, pageY) => {
        setTriggerPosition({ width, pageX, pageY: pageY, height });
      });
      const newValue = !open;
      onOpenChange(newValue);
      onPressProp?.(ev);
    }

    const Component = asChild ? Slot.Pressable : Pressable;
    return (
      <Component
        ref={augmentedRef}
        aria-disabled={disabled ?? undefined}
        role='button'
        onPress={onPress}
        disabled={disabled ?? undefined}
        aria-expanded={open}
        {...props}
      />
    );
  }
);

//...

// The imported "Slot.Pressable"
const Pressable = React.forwardRef<React.ElementRef<typeof RNPressable>, RNPressableProps>(
  (props, forwardedRef) => {
    const { children, ...pressableSlotProps } = props;

    if (!React.isValidElement(children)) {
      console.log('Slot.Pressable - Invalid asChild element', children);
      return null;
    }

    return React.cloneElement<
      React.ComponentPropsWithoutRef<typeof RNPressable>,
      React.ElementRef<typeof RNPressable>
    >(isTextChildren(children) ? <></> : children, {
      ...mergeProps(pressableSlotProps, children.props as AnyProps),
      ref: forwardedRef ? composeRefs(forwardedRef, (children as any).ref) : (children as any).ref,
    });
  }
);
```
https://github.com/roninoss/rn-primitives/blob/main/packages/dropdown-menu/src/dropdown-menu.tsx

**Comment by latekvo** [comment]
@tannerbaum 

The `@rn-primitves` pressable doesn't seem to be working as a standalone element. I think it might be designed to be used only with other components provided `@rn-primitives`?

Would you be able to provide a minimal reproduction of the bug you encountered?
Just going off your description, without any extra data, it seems like `@rn-primitives` Pressable is broken regardless of our doing.

Here is the repro I used:

<details>

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Pressable as SlotPressable } from '@rn-primitives/slot';

const SECTION_RADIUS = 40;
const BASE_SIZE = 120;

export default function PressableExample() {
  const pressIn = () => {
    console.log('Pressable pressed in');
  };

  const pressOut = () => {
    console.log('Pressable pressed out');
  };

  const press = () => {
    console.log('Pressable pressed');
  };

  const hoverIn = () => {
    console.log('Hovered in');
  };

  const hoverOut = () => {
    console.log('Hovered out');
  };

  const longPress = () => {
    console.log('Long pressed');
  };
  return (
    <View style={{ flex: 1, backgroundColor: 'white' }}>
      <View style={styles.pressRectContainer}>
        <View style={styles.hitRectContainer}>
          <SlotPressable
            style={styles.pressable}
            onPressIn={pressIn}
            onPressOut={pressOut}
            onPress={press}
            onHoverIn={hoverIn}
            onHoverOut={hoverOut}
            onLongPress={longPress}
            hitSlop={SECTION_RADIUS}
            pressRetentionOffset={SECTION_RADIUS}>
            <View style={styles.textWrapper}>
              <Text style={styles.text}>Pressable!</Text>
            </View>
          </SlotPressable>
          <Text style={styles.rectText}>Hit Rect</Text>
        </View>
        <Text style={styles.rectText}>Press Rect</Text>
      </View>
    </View>
  );
}

const BACKGROUND_COLOR = '#F5FCFF';

const styles = StyleSheet.create({
  pressRectContainer: {
    backgroundColor: '#FFD6E0',
    padding: SECTION_RADIUS,
    width: BASE_SIZE + 4 * SECTION_RADIUS,
    height: BASE_SIZE + 4 * SECTION_RADIUS,
    margin: 'auto',
  },
  hitRectContainer: {
    backgroundColor: '#F29DC3',
    padding: SECTION_RADIUS,
    width: BASE_SIZE + 2 * SECTION_RADIUS,
    height: BASE_SIZE + 2 * SECTION_RADIUS,
    margin: 'auto',
  },
  rectText: {
    color: BACKGROUND_COLOR,
    fontWeight: '700',
    position: 'absolute',
    right: 5,
    bottom: 2,
  },
  pressable: {
    width: BASE_SIZE,
    height: BASE_SIZE,
    backgroundColor: 'mediumpurple',
  },
  highlight: {
    width: BASE_SIZE,
    height: BASE_SIZE,
    backgroundColor: 'red',
  },
  textWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    color: BACKGROUND_COLOR,
  },
});

```

</details>

---

Now that I'm testing it more, the `@rn-primitves` pressable actually seems very unpredictable.
Functional styling doesn't work, sometimes it crashes, sometimes it throws `invalid asChild undefined` err, sometimes it simply doesn't react to any interaction.

**Comment by Qdafengzi** [comment]
"react-native-gesture-handler": "2.26.0",

maybe this probelm have been fixed in new version ,

my version:
RN 0.79.2 + RNGH 2.26.0

**Comment by vendramini** [comment]
> Please let me know if [#3571](https://github.com/software-mansion/react-native-gesture-handler/pull/3571) works on your setups.
> 
> Tested it on the repro sent by [@baylesa-dev](https://github.com/baylesa-dev) and it now seems to be working well. Also tested with our example app on every supported platform, and haven't found any new issues.
> 
> (c.c. [@vendramini](https://github.com/vendramini), [@techied](https://github.com/techied))

Haven't got any issue so far 🥇 Thank you @latekvo !

**Comment by latekvo** [comment]
The `Release 2.27.0` is now live with a fix for this issue.

**Comment by gigobyte** [comment]
@latekvo The `/lib` folder is missing from the 2.27.0 release, possibly a bad build?

**Comment by khushal87** [comment]
Does it solve the issue if `react-native` pressable is used as well?

**Comment by latekvo** [comment]
@khushal87 which issue are you referring to?

If you have a working reproduction example, please feel free to open an issue in this repository.

**Comment by khushal87** [comment]
Hey @latekvo, I have a scenario where a similar issue seems to occur if I am using the `Pressable` from React Native as well, where the taps are unresponsive inside the `GestureDetector`, specifically on Android 14 devices.

**Comment by latekvo** [comment]
@khushal87 The RN Pressable uses a `Pressability API` for handling interactions. It is incompatible with our gesture handling logic. It's difficult to tell if the issue you're referring to is expected behaviour, or an unexpected problem without specific details on how you're trying to use and combine the components. I urge you to open an issue with a minimal reproduction. That'll make sure we're able to help you.

**Comment by proambb** [comment]
> Hey [@latekvo](https://github.com/latekvo), I have a scenario where a similar issue seems to occur if I am using the `Pressable` from React Native as well, where the taps are unresponsive inside the `GestureDetector`, specifically on Android 14 devices.

We also had such a problem with ReactNative (RN) `Pressable` component used inside `Swipeable` ReactNativeGestureHandler (RNGH) component and all of them were inside RN `FlatList`. After a few mounts and unmounts the press event was not fired.
It happened on RN version `0.76` and it happened on RN `0.79` with the latests RNGH (version `2.28.0`). 

The only thing that helped on all the versions is to use `Pressable` from RNGN. 

Unfortunately, it's not easy to reproduce on some simple app and I cannot provide reproducible example, but can confirm that RN `Pressable` sometimes does not work well with RNGH.

**Comment by mordechaim** [comment]
I'm experiencing this same issue intermittently on Expo 54 with RNGH 2.28.0. Very hard to reproduce as it generally works but then stops firing any event without warning.

On a release build it **NEVER** works! No events fired.

RN Pressable does work as expected.

Worth mentioning, in LogCat it logs the press in and out, but in react native no event gets propogated

**Comment by latekvo** [comment]
Hi @mordechaim , would you mind sharing a reproduction of this issue?
It's difficult to act on this issue without pinning down the root cause.
We've been dealing with similar issues in the past, although they were mostly related to the `RectButton` and other similar components we expose, and not necessarily the `Pressable` itself. While we resolved most of them, some could've been either missed or regressed. 

Also, one last thing:
>On a release build it NEVER works!

Do you mean that the feature never works, or that the reproduction never works?

---

Hey @davoam, do I understand correctly that replacing RN `Pressable` with RNGH `Pressable` fixed your issue? It sounds a bit like an issue with RN, and not RNGH, but I could be wrong, since you're also using our `Swipeable` which could have some indirect impact on the whole thing. Also, just to make sure, are you using the `Swipeable` or the `ReanimatedSwipeable`? If you don't mind, I'd really appreciate a reproduction for this issue, and if you have some time on hand, even a github issue. That way, we'll be able to help you faster.

**Comment by mordechaim** [comment]
I'll try to make a reproduction soon.

I checked on Expo 54 Android release build and Pressable doesn't fire any events. I'm now working on downgrading to figure out if Expo 54 broke things.

**Comment by tomkelsey** [comment]
> I'll try to make a reproduction soon.
> 
> I checked on Expo 54 Android release build and Pressable doesn't fire any events. I'm now working on downgrading to figure out if Expo 54 broke things.

Just to add - Expo 54 for me and RNGH Pressable doesn’t work on Android on release builds.

Works in dev mode.

Works on iOS (dev and release).

It worked prior to upgrading Expo (and other deps).

I haven’t had a chance to debug yet as to cause so was holding off saying anything but as someone else mentioned something very similar I thought I’d comment.

**Comment by latekvo** [comment]
@tomkelsey @mordechaim 
I created a fresh Expo `54.0.10` app with `react-native-gesture-handler 2.28.0`. I've built a release build of said app and installed it on my phone. Every Pressable callback seems to be firing well.

If you're still encountering these issues on the latest version of Expo, then please open an issue with a minimal reproduction, this way we can pinpoint the issue and try to fix it as fast as possible. Without a minimal reproduction, there isn't much i can do to help you.

**Comment by mordechaim** [comment]
Yeah I did the same and it did work.

I suspect it's Nativewind that messes around here. I wasn't available the last few days to work on a minimal reproduction, I'll get to it soon.

@tomkelsey do you use Nativewind?

**Comment by tomkelsey** [comment]
Hey @latekvo and @mordechaim 

Not using Nativewind here.

I still haven't fully got to the bottom of it but it appears in our case to relate to react-native-picker (https://github.com/react-native-picker/picker)

I was able to reproduce the issue as follows:

1. npx create-expo-app@latest
2. Installed/setup RNGH
3. Added a simple `<Pressable>` from RNGH onto the home screen
4. Install @react-native-picker/picker (but didn't include it anywhere, just npm install)

Then when I built for release on android and tested on device, Pressable didn't work.

Other findings:
- Worked fine in dev on emulator/device
- Worked fine on iOS dev or release
- RectButton from RNGH still worked
- Pressable from react-native itself still worked.

Not sure how all the underlying bits work as to what may cause the above. But uninstalling @react-native-picker/picker caused Pressable to work again 🤷‍♂️

**Comment by mordechaim** [comment]
Indeed I do have react native picker installed. Perhaps @tomkelsey you can open a new issue with this reproduction

**Comment by latekvo** [comment]
Hey @tomkelsey, thanks for that info, that's very useful. I'll reopen this issue for now due to traffic.

**Comment by iankberry** [comment]
> > I'll try to make a reproduction soon.
> > I checked on Expo 54 Android release build and Pressable doesn't fire any events. I'm now working on downgrading to figure out if Expo 54 broke things.
> 
> Just to add - Expo 54 for me and RNGH Pressable doesn’t work on Android on release builds.

Just made my first release build with Expo 54 on Android and am experiencing the exact same issue. Everything is totally normal with emulator/device dev builds but Pressables don't fire any events on a release build.

Not to complicate things either but I am **not** using the `@react-native-picker/picker` library. Maybe whatever the underlying issue has a broader cause. Happy help reproduce this too but am not sure the best way to go about that for an issue that only occurs on release builds.

**Comment by mrv777** [comment]
Just another confirmation here, removing `@react-native-picker/picker` made the pressable from RNGH work again on android devices for me with Expo 54

**Comment by tomkelsey** [comment]
> > > I'll try to make a reproduction soon.
> > > I checked on Expo 54 Android release build and Pressable doesn't fire any events. I'm now working on downgrading to figure out if Expo 54 broke things.
> > 
> > 
> > Just to add - Expo 54 for me and RNGH Pressable doesn’t work on Android on release builds.
> 
> Just made my first release build with Expo 54 on Android and am experiencing the exact same issue. Everything is totally normal with emulator/device dev builds but Pressables don't fire any events on a release build.
> 
> Not to complicate things either but I am **not** using the `@react-native-picker/picker` library. Maybe whatever the underlying issue has a broader cause. Happy help reproduce this too but am not sure the best way to go about that for an issue that only occurs on release builds.

I uninstalled half the dependencies that had a native element, built the app and tested to see if it worked then rinse and repeat until I narrowed it down to what was causing the problem. It sounds like multiple dependencies may cause some sort of conflict?

It was particularly unfun and time consuming (not to mention I didn't know it was definitely a dependency conflict) so if anyone knows a better way for future reference I'm all ears!

**Comment by iankberry** [comment]
> I uninstalled half the dependencies that had a native element, built the app and tested to see if it worked then rinse and repeat until I narrowed it down to what was causing the problem. It sounds like multiple dependencies may cause some sort of conflict?
> 
> It was particularly unfun and time consuming (not to mention I didn't know it was definitely a dependency conflict) so if anyone knows a better way for future reference I'm all ears!

After going through the same trial and error process, I was able to narrow it down to a single dependency: [@s77rt/react-native-date-picker](https://github.com/s77rt/react-native-date-picker). Different library but same situation. If I remove this library everything works. Otherwise I have the pressable issue. In my case, I could probably replace this library but I really wonder what's going on. There must be something on the native side that is interfering with the gesture handler library in some way on newer versions of Expo/RN.

**Comment by JamesMahy** [comment]
> > I uninstalled half the dependencies that had a native element, built the app and tested to see if it worked then rinse and repeat until I narrowed it down to what was causing the problem. It sounds like multiple dependencies may cause some sort of conflict?
> > It was particularly unfun and time consuming (not to mention I didn't know it was definitely a dependency conflict) so if anyone knows a better way for future reference I'm all ears!
> 
> After going through the same trial and error process, I was able to narrow it down to a single dependency: [@s77rt/react-native-date-picker](https://github.com/s77rt/react-native-date-picker). Different library but same situation. If I remove this library everything works. Otherwise I have the pressable issue. In my case, I could probably replace this library but I really wonder what's going on. There must be something on the native side that is interfering with the gesture handler library in some way on newer versions of Expo/RN.

I'm not using that dependency or `@react-native-picker/picker` and have the same issue.
I am using https://github.com/henninghall/react-native-date-picker but removing it doesn't fix the issue for me.

It's only on iOS it seems and not all of my users experience it. After some debugging the Pressable doesn't fire the onPress event at all. It's random and smashing it repeatedly seems to make it work.

It only happens in Modal lists though...

It also happens if I switch to a TouchableOpacity

**Comment by StormeNet** [comment]
I'm neither using `@react-native-picker/picker` nor `[@s77rt/react-native-date-picker](https://github.com/s77rt/react-native-date-picker)` but also encounter this issue on iOS. 
I am using Flatlist, and for me it's not directly linked to modal. 

Once it starts happening, the whole app is encountering issues, some buttons work, some half, some not at all. Only remedy for the user is to close the app and re-open

**Comment by Sydney-o9** [comment]
We have the same issue here on Android only in release target, not debug.

```shell
# Tappable works on a Debug build
./gradlew assembleDebug

# Tappable doesn't work on a Release build
./gradlew assembleRelease
```

Unfortunately this bug started on Apr-6 about 6 months ago. The danger here is that it is totally feasible for anyone to push a build to prod with all buttons un-clickable. Google Play would only report off un-clickable buttons days after the release.

**Comment by m-bert** [comment]
Hi! I've looked into this issue as it seems quite strange that simply adding new library breaks our functionality.

For now I've managed to find out that the problem starts from `React Native 0.81`. `0.80` and below should work fine. I'm not sure what broke though, it might be the case that `@react-native-picker/picker` (and possibly other libraries) have native components which in some way don't work with our button, but it is just a guess. 

Right now it is hard to say whose fault it is. I'll get back here if I find anything else.

**Comment by JamesMahy** [comment]
> Hi! I've looked into this issue as it seems quite strange that simply adding new library breaks our functionality.
> 
> For now I've managed to find out that the problem starts from `React Native 0.81`. `0.80` and below should work fine. I'm not sure what broke though, it might be the case that `@react-native-picker/picker` (and possibly other libraries) have native components which in some way don't work with our button, but it is just a guess.
> 
> Right now it is hard to say whose fault it is. I'll get back here if I find anything else.

I'm on React Native 0.76 and it's not an issue on Android with the old architecture but it is on iOS with the new Architecture.

**Comment by jerone** [comment]
We appear to also have issues with Pressables not being able to press anymore, after upgrading to Expo 54 with RN 0.81.

Our tests indicate it's only an Android issue on Expo Go:

<table>
<tr>
 <th>OS
 <th>Run as
 <th>Device
 <th>Result
<tr>
 <td>Android
 <td>Expo Go
 <td>Physical
 <td>❌
<tr>
 <td>Android
 <td>Expo Go
 <td>Emulator
 <td>❌
<tr>
 <td>Android
 <td>Dev Build
 <td>Physical
 <td>✅
<tr>
 <td>Android
 <td>Dev Build
 <td>Emulator
 <td>✅
<tr>
 <td>iOS
 <td>Expo Go
 <td>Physical
 <td>✅
<tr>
 <td>iOS
 <td>Expo Go
 <td>Simulator
 <td>✅
<tr>
 <td>iOS
 <td>Dev Build
 <td>Simulator
 <td>✅
</table>

All tests have been executed on minimum 2 physical or 2 emulators.

**Comment by alterx** [comment]
Just another confirmation here:

We had `@react-native-picker/picker` as part of our dependencies and I started having this issue with Expo 54 and RN 0.81.4.
Gladly, the picker dependency was a leftover that we no longer used so I removed it and voilà, the `Pressable` issue  on Android is gone

**Comment by tomkelsey** [comment]
The latest version of `react-native-picker` (https://github.com/react-native-picker/picker) v2.11.3 appears to have fixed this issue for me.

Looks like it included this PR (https://github.com/react-native-picker/picker/pull/648) regarding target_compile_reactnative_options

Hopefully helps point people in the right direction if they were having the same issue with other libraries.

**Comment by m-bert** [comment]
Thank you for spotting this @tomkelsey! I have not tested that yet, but it makes sense that this could help. I'll give it a try tomorrow.

**Comment by m-bert** [comment]
Actually, I've managed to check that today. Seems like it does work. I'm closing this issue. If it persists, let me know!

**Comment by Mokhtar25** [comment]
I can confirm that the issue persists after updating both packages(picker and rngh). After updating the picker to v2.11.4. it started working in more placses but the button did not work when displayed inside a modal in my case inside a react native Modal component.

**Comment by williamsaar** [comment]
We're on RNGH 2.28 and still experiencing an issue. We are using a modal lib (@gorhom/bottom-sheet) with a pressable button to close the modal. When clicking it on android it sometimes "gets stuck" with the ripple on it and all other pressables stops responding to onClick-events.

**Comment by Bowlerr** [comment]
Having a similar issue with react native 0.76.9 and 2.30. caused by spamming open and close a flatlist with pressables in a modal

handlePressIn / NATIVE_BEGIN is never being called therefore it ignores the pressout.

 pressAndTouchGesture - onTouchesDown
 LOG  STATE_EVENT {"eventName": "longPressTouchesDown", "expected": "nativeBegin", "stepIndex": 0}
 LOG  STATE_EVENT_MISMATCH {"eventName": "longPressTouchesDown", "expected": "nativeBegin", "stepIndex": 0}
 LOG  buttonGesture - onTouchesCancelled {"nativeEvent": {"changedTouches": [[Object]], "force": undefined, "identifier": 178, "locationX": 117.154296875, "locationY": 32.33538055419922, "pageX": 149.154296875, "pageY": 200.3353729248047, "target": 0, "timestamp": 1768491637412, "touches": [[Object]]}}
 LOG  handlePressOut called
 LOG  Ignoring pressOut because isCurrentlyPressed is false
 LOG  pressAndTouchGesture - onTouchesUp

**Comment by Bowlerr** [comment]
Nevermind, I didn't refresh my node-modules in my example app properly. Seems to be fine now on 2.30.0
