### ISSUE TITLE
Nested Pressable behaviour different between RNGH and RN

### ISSUE THREAD

**Issue by Bekaxp** [software-mansion/react-native-gesture-handler#3547]
### Description

I noticed that the `Pressable` component works differently between RNGH and RN. When we nest one inside the other the events propagation is different. With RNGH, when the inner Pressable is pressed it triggers the outer as well, while using Pressable from RN this doesn't happen.
I am questioning which implementation is right? is there a bug with RNGH? Is there a way to make it behave the same as in RN?

Here is a video showing the difference:
https://github.com/user-attachments/assets/a9be5b31-659e-4cdf-a1c2-da1aa4cce45f

### Steps to reproduce

1. Create a composition where you have a Pressable component nested inside another Pressable.
2. Press the inner Pressable, you will notice that also the outer `onPress` event was called.
3. Change the Pressable component to the one from React Native instead of the one from RNGH.
4. Try again pressing the inner Pressable, you can notice that the outer Pressable `onPress` was not triggered.

### A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.

https://snack.expo.dev/@bekaxp/eager-orange-hummus

### Gesture Handler version

~2.24.0

### React Native version

0.79

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

New Architecture (Fabric)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Bekaxp! Have you tried Gesture Handler 2.25.0? It includes [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/3295) which should fix this issue 😅

**Comment by Bekaxp** [comment]
Hi, thank you for your input. I created a fresh RN project with all the latest dependencies (also RNGH v2.25.0) and now it seems it works as expected. I will do some more testing but I think we can close this one.

Thank you for the quick support 👍

**Comment by lucidkodo** [comment]
This issue persists for me in both 2.25.0 and 2.24.0 versions. 

Expo: 52.0.41
Arch: Old (Paper)
RN: 0.76.9
Platform: iOS + Android

**Comment by m-bert** [comment]
@lucidkodo does it happen on newer RN versions?

**Comment by lucidkodo** [comment]
> [@lucidkodo](https://github.com/lucidkodo) does it happen on newer RN versions?

@m-bert i haven't got time to test that yet, but will let you know once i do.
