### ISSUE TITLE
null is not an object ( evaluating 'RNGestureHandlerModule.Direction')

### ISSUE THREAD

**Issue by blackpencil8994** [software-mansion/react-native-gesture-handler#494]
Hi, 
I'm using `react-native-gesture-handler` within `react-navigation` and getting this error 

> null is not an object ( evaluating 'RNGestureHandlerModule.Direction')

![screen shot 2019-03-05 at 1 27 51 am](https://user-images.githubusercontent.com/24391349/53754681-40f9f000-3ee7-11e9-9321-ad2e0673fe3c.png)

my project is just simple and using the latest release of react-native-gesture-handle 

`...
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-gesture-handler": "^1.1.0",
    "react-navigation": "^3.3.2"
  },
...
`
Seem it's related to Direction.js fix web compatibility #406

Any suggestion for me to fix this?

**Comment by hamedhemmati** [comment]
I am getting the same error.

**Comment by ajboxjr** [comment]
Have you tried this? This solved my problem

1. Right Click Libraries "Add Files to Project"
2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
3. Go to build phases and add libRNGestureHandler.a
4. Run
Good luck to you all!

**Comment by hamedhemmati** [comment]
Thank you for the quick response that solved the problem for me.

**Comment by blackpencil8994** [comment]
Thanks @ajboxjr for your help,

I did follow your step and successfully run by XCode.

But it's stil not working with `react-native run-ios`

**Comment by blackpencil8994** [comment]
Finally I did the same with new project and it worked for me.

So we need to **manual linking** `react-native-gesture-handler` with this new version 

Thank you all.

**Comment by amrita6** [comment]
Hi, I have the same issue in Android app. Could you please help me to fix it?

**Comment by blackpencil8994** [comment]
@amrita6  you can link automatically in Android. But you need to manual link in iOS project.
After install package, try this:

1. Manual link for iOS project in XCode
2. Rename **ios** folder into **iosX**
3. Automatically link for Android by `react-native link react-native-gesture-handler`
4. Rename  **iosX** folder into **ios** in turn
5. Run

Hope this helps.

**Comment by amrita6** [comment]
@blackpencil8994 thanks but I needed Android only.
I have found the reason already: in /android/settings.gradle there was string:
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')

I've changed this to:
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\\node_modules\\react-native-gesture-handler\\android')

and this helped me. Strange that it has happened so.

**Comment by markhker** [comment]
> @blackpencil8994 thanks but I needed Android only.
> I have found the reason already: in /android/settings.gradle there was string:
> project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')
> 
> I've changed this to:
> project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')
> 
> and this helped me. Strange that it has happened so.

Two strings are the same...

**Comment by amrita6** [comment]
@markhker strange but there was two backslashes but it showed as one. I've changed it already.

**Comment by joshverd** [comment]
I'm still getting this after trying everything above, same versions as mentioned previously.

**Comment by JosephDunivan** [comment]
I'm having this same issue. Why would I need to manually link in iOS. I actually went into my xCode project and its linked fine.

**Comment by JosephDunivan** [comment]
I looked in `GestureHandler.js` and its says import Directions from `./Directions;`, but no such object `Directions` exists in `Directions.js.` It sets NativeModules from react-native to `RNGestureHandlerModule` with method `.Direction` (which doesn't exist). Produces error `null is not and object (evaluating 'RNGestureModule.Direction')`

**Comment by denieler** [comment]
same issue here :(

**Comment by denieler** [comment]
ok, in my case solved by adding:
```
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
....
protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
            ....
            new RNGestureHandlerPackage()
        );
    }
```
to `android/app/src/main/java/com/projectname/MainApplication.java`

**Comment by joshverd** [comment]
I ended up just giving up and building my own navigation component, haha.

**Comment by cyphire** [comment]
I may have the answer to this!!!!

I was in some of my ES6 constants file... and I added a TouchableOpacity by accident, instead of the usual TouchableHighlight in some JSX.

My editor (Visual Studio Code) seemed to have added:
`
import { TouchableOpacity } from 'react-native-gesture-handler';

`at the top of my file!!!  WIthout my asking for it!

Go see if this was put into your code by accident, got the same error as all of you!  Nothing to do with some of these comments!

It also puts an erronous console import as well when i use console for the first time in a file!

Anyway, had the error, noticed the bad import at the top and now all ok!!!

**Comment by darbio** [comment]
> Have you tried this? This solved my problem
> 
> 1. Right Click Libraries "Add Files to Project"
> 2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 3. Go to build phases and add libRNGestureHandler.a
> 4. Run
>    Good luck to you all!

Where do you do this? In XCode?

**Comment by darbio** [comment]
For other people, rebuilding and deploying from XCode solved this issue for me. I didn't realise that once you link, you need to re-build and deploy (which makes total sense now that I understand _what_ linking is!)

**Comment by tansangxtt** [comment]
> Hi,
> I'm using `react-native-gesture-handler` within `react-navigation` and getting this error
> 
> > null is not an object ( evaluating 'RNGestureHandlerModule.Direction')
> 
> ![screen shot 2019-03-05 at 1 27 51 am](https://user-images.githubusercontent.com/24391349/53754681-40f9f000-3ee7-11e9-9321-ad2e0673fe3c.png)
> 
> my project is just simple and using the latest release of react-native-gesture-handle
> 
> `... "dependencies": { "react": "16.6.3", "react-native": "0.58.6", "react-native-gesture-handler": "^1.1.0", "react-navigation": "^3.3.2" }, ... `
> Seem it's related to Direction.js fix web compatibility #406
> 
> Any suggestion for me to fix this?

Hi @blackpencil8994,

I also got this problem, but it can be run by `react-native run-ios/android`. Could you run it with Metro Bundler?

**Comment by jin-benben** [comment]
I am getting the same error in android

**Comment by khattab93** [comment]
After I followed the steps here `https://reactnavigation.org/docs/en/getting-started.html`, I got the same issue and I solved it as follows:
1- Manually linking RNGestureHandler in Xcode (Apply @ajboxjr solution with the steps mentioned here `https://facebook.github.io/react-native/docs/linking-libraries-ios`) 
2- Uninstall the app 
3- Rebuild and rerun the app using Xcode

**Comment by thefiscina** [comment]
https://pt.stackoverflow.com/questions/345084/undefined-is-not-an-object-evaluating-rngesturehandlermodule-state

Funcionou para mim no android! 
It worked for me on Android!

**Comment by Gauravmokashi** [comment]
> I am getting the same error in android

Have you solve this?

**Comment by Gauravmokashi** [comment]
> Have you tried this? This solved my problem
> 
> 1. Right Click Libraries "Add Files to Project"
> 2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 3. Go to build phases and add libRNGestureHandler.a
> 4. Run
>    Good luck to you all!

which libraries you are talking about?

**Comment by kidmysoul** [comment]
in android、I　resolved it by `react-native start --reset-cache`

**Comment by osdnk** [comment]
So AFAIK it's just a matter of restarting and rebuilding.

**Comment by orsospatrick** [comment]
On Android for this I used :  react-native link react-native-gesture-handler after installed react-native-gesture-handler and I solve the problem.

**Comment by HunnainKhan** [comment]
For my just running 
react-native link 
command worked for me after re installing some libraries like react navigation

**Comment by endritvitija** [comment]
run in terminal " react-native link react-native-gesture-handler " if not work check this guide https://reactnavigation.org/docs/en/getting-started.html

**Comment by sasurau4** [comment]
I faced with the same problem and this comment works for me 👍 
https://github.com/kmagiera/react-native-gesture-handler/issues/494#issuecomment-471164413

If someone faced with the problem, please check your `android/app/src/main/java/com/projectname/MainApplication.java`.

**Comment by aprofromindia** [comment]
> ok, in my case solved by adding:
> 
> ```
> import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
> ....
> protected List<ReactPackage> getPackages() {
>         // Add additional packages you require here
>         // No need to add RnnPackage and MainReactPackage
>         return Arrays.<ReactPackage>asList(
>             ....
>             new RNGestureHandlerPackage()
>         );
>     }
> ```
> to `android/app/src/main/java/com/projectname/MainApplication.java`

I think I need to do the same, but I am trying to integrate RN in an existing project [using this guideline](https://facebook.github.io/react-native/docs/integration-with-existing-apps) and though I implement ReactApplication in my custom Application class the getReactNativeHost() method never gets triggered, any ideas here ?

**Comment by bonnmh** [comment]
> ok, in my case solved by adding:
> 
> ```
> import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
> ....
> protected List<ReactPackage> getPackages() {
>         // Add additional packages you require here
>         // No need to add RnnPackage and MainReactPackage
>         return Arrays.<ReactPackage>asList(
>             ....
>             new RNGestureHandlerPackage()
>         );
>     }
> ```
> to `android/app/src/main/java/com/projectname/MainApplication.java`

Can you show me the mainactivity

**Comment by potatowave** [comment]
I am finding the same issue on ios when running with `react-native run-ios`.  The app does run from the xcode workspace, however I need to have it running on a remote build server.

Has anyone in this situation been able to solve this issue?

**Comment by osdnk** [comment]
Do maybe it’s a problem with linking on your remote server?

**Comment by potatowave** [comment]
I don't think so.

**Run Locally with Xcode:**  Works
**Run Locally with `react-native run-ios`:**  This error
**Run Remotely with `react-native run-ios`:**  Presumed this error (app crashes before I can get any diagnostics)

**Comment by osdnk** [comment]
https://stackoverflow.com/questions/35611765/react-native-run-ios-command-fails-pch-issues-but-build-succeeds-in-xcode

Maybe?

**Comment by potatowave** [comment]
I have tried deleting build.  The build succeeds when running `react-native run-ios` however the simulator still loads with this `null is not an object ( evaluating 'RNGestureHandlerModule.Direction')` error.

Pretty sure it's some kind of linking issue.  Does `react-native run-ios` look at different configs or something?

**Comment by osdnk** [comment]
It does not have another config. But it has another cache

**Comment by SynQi** [comment]
> 
> 
> https://pt.stackoverflow.com/questions/345084/undefined-is-not-an-object-evaluating-rngesturehandlermodule-state
> 
> Funcionou para mim no android!
> It worked for me on Android!

Valeu irmão ! salvou hard hehe

**Comment by vvavdiya** [comment]
I have solved this error by manually linking `react-native-gesture-handler`

as per [React-Navigation setup guide](https://reactnavigation.org/docs/en/getting-started.html#installation)

```
package com.sperapp;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "SperApp";
    }
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}
```

**Comment by davesimtech** [comment]
I had this issue with iOS when trying to get it running. After following the installation instructions and linking with

`react-native link react-native-gesture-handler`

I then had to run

`pod install`

Maybe the instructions need to be updated to reflect this if you are using pods?

**Comment by awesomeo99** [comment]
> Finally I did the same with new project and it worked for me.
> 
> So we need to **manual linking** `react-native-gesture-handler` with this new version
> 
> Thank you all.

can you elaborate on this?
were you trying to run on iOS or Android?

**Comment by agm1984** [comment]
`pod install` fixed my issue for iOS. Android was working fine after following the instructions at https://reactnavigation.org/docs/en/getting-started.html.

Here is what I saw:
![image](https://user-images.githubusercontent.com/17655219/56637987-d54c1d80-6621-11e9-9368-d97ec12146d3.png)

**Comment by rahulpsd18** [comment]
Getting the same issue on android. using version 1.1.0
Followed all steps I could find here or on SO, unlinked, uninstalled then reinstalled and relinked.
Did it manually too, restarted the build process, restarted the PC, ran `gradlew clean` and still facing the issue. Any help would be appreciated.

**Comment by arled** [comment]
**Thank me later:**
`yarn add react-native-gesture-handler`
`react-native link react-native-gesture-handler`
`react-native run-ios`
_No need for silly manual steps as above._
You're welcome!

**Comment by dksami** [comment]
Simply open xcode still dosent work, go to library and add a file, in file selector nevigate to genturehandler inside node module and then select that xcodeproject and then build basic, nevigate to library section and add the the module from library.

**Comment by erikadelao13** [comment]
> 
> 
> Have you tried this? This solved my problem
> 
>     1. Right Click Libraries "Add Files to Project"
> 
>     2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 
>     3. Go to build phases and add libRNGestureHandler.a
> 
>     4. Run
>        Good luck to you all!

which IDE are you using? i am on vs code and i dont know where i should do this

**Comment by alpaca623** [comment]
> @amrita6 you can link automatically in Android. But you need to manual link in iOS project.
> After install package, try this:
> 
> 1. Manual link for iOS project in XCode
> 2. Rename **ios** folder into **iosX**
> 3. Automatically link for Android by `react-native link react-native-gesture-handler`
> 4. Rename  **iosX** folder into **ios** in turn
> 5. Run
> 
> Hope this helps.

your solutaion very nice. Thank you.

And, I have question. Why did you rename the ios folder and link? And.. why linking work is not working well? How was this resolved? 
Thank you very much for your reply.

**Comment by mkcode** [comment]
I suspect whether or not the `pod install` works or does not will be related to which version of Cocoapods you are running

**Comment by ph1p** [comment]
I fixed it by editing the `MainApplication.java`.

**Add this:**
```
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
```

**And this:**
```
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new RNGestureHandlerPackage()
    );
}
```

**Comment by SirCameron** [comment]
> Have you tried this? This solved my problem
> 
>     1. Right Click Libraries "Add Files to Project"
> 
>     2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 
>     3. Go to build phases and add libRNGestureHandler.a
> 
>     4. Run
>        Good luck to you all!

Thanks, dude!!

**Comment by AlexanderThiele** [comment]
i had this issue for days and it seems that my issue was not to properly link the library.
I solved it by providing the gestureHandler package when i initialise the view inside my activity

This is the block for creating the react view 
```
    mReactRootView = new ReactRootView(this);
    mReactInstanceManager = ReactInstanceManager.builder()
        .setApplication(getApplication())
        .setCurrentActivity(this)
        .setBundleAssetName("index.android.bundle")
        .setJSMainModulePath("index")
        .addPackages(Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNGestureHandlerPackage()
        ))
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(LifecycleState.RESUMED)
        .build();
    mReactRootView.startReactApplication(mReactInstanceManager, "AwesomeProject", null);
```

The important part is passing the RNGestureHandlerPackage to React Native (instead of providing it on Application level):
```
    .addPackages(Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNGestureHandlerPackage()
        ))
```

Maybe this will save someone's time 👍

**Comment by Nextt1** [comment]
Same issue. I am using `react-native-navigation`. I added `new RNGestureHandlerPackage()` but in that case, I'm getting ` package com.swmansion.gesturehandler.react does not exist` error.

**Comment by immortalx** [comment]
In react-native v0.60.0 RC 0 i had to run pod install in the ios directory and it worked fine. 
I was getting the same error with just react-native link.

**Comment by lucascaton** [comment]
My 2 cents:

First, I was getting the above error (`null is not an object ( evaluating 'RNGestureHandlerModule.Direction')`).

Then, when I opened Xcode and tried building/running the project, the following error was showing up:

`unable to read property list from file: (...)/ios/<project>/Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.)`

There was a formatting error indeed inside my `Info.plist` file. In order to find out what and where was it, I ran:

```sh
/usr/bin/plutil -lint ios/<project>/Info.plist
```

This command told me exactly in which like the issue was! 🎉

Hope it helps someone else with the same issue :)

**Comment by santaclauze** [comment]
What worked for me for WebStorm and Android-studio emulator:

    react-native start --reset-cache
    react-native link
    npm start

**Comment by WChambers** [comment]
Another solution specific for Cocoapod implementations: Do not ignore the warnings after a `pod install`. I don't use cocoapods often so it is easy to breeze past the list of `<target> overrides <setting>` warnings. 

Once I corrected each those for my target (I think OTHER_LDFLAGS was the main culprit), things appear to be working fine. This was accomplished via react-native link.

**Comment by volokolamskspb** [comment]
This thing worked for me:
Go to `node_modules/react-native-gesture-handler/GestureHandler.js`
And commit this line 
`
//export { default as Directions } from './Directions';
`

**Comment by sirisec** [comment]
There seems to be a distinct differences when using react-native 0.60.0 (current release) vs 0.59.9.

I was not able to get it to work at all in the 0.60.0 version, but the same code and install commands work perfectly for 0.59.9.

Posting as it may save someone some trouble.

**Comment by mgfjxxiexiaolong** [comment]
> I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> 
> `react-native link react-native-gesture-handler`
> 
> I then had to run
> 
> `pod install`
> 
> Maybe the instructions need to be updated to reflect this if you are using pods?

谢谢！我在向现有app中引入了RN，在执行离线包的时候遇到了这个问题，`react-native link`操作后一定要执行`pod install`，我的问题很好的解决了。

**Comment by dallasclark** [comment]
Thanks @HunnainKhan !

**Comment by johnnfujita** [comment]
for ios:
>>> yarn add react-navigation
>>> yarn add react-native-gesture-handler
>>> react-native link react-native-gesture-handler

if it is not working:

go into ./project_folder/ios_folder/
>>> pod install

This worked for me today... but actually the instructions on the website were working for me on my regular workstation. Software is so temperamental. ehehehehehhe..

**Comment by developerewt** [comment]
I was getting this error in iOS build. I ran `pod install` inside my ios folder and it worked.

I will run my project in iOS and Android, because of this I followed all steps in installation documentation, including the modification of MainActivity.java.

**Comment by Harsh2402** [comment]
Looks like this is to do with the new autolinking feature in RN 0.60. To fix for now just add the following podspec for RNGesureHandler to ios/Podfile

```
pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
```

Then in the ios directory run pod install to install it.

**Comment by bobzhen** [comment]
> I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> 
> `react-native link react-native-gesture-handler`
> 
> I then had to run
> 
> `pod install`
> 
> Maybe the instructions need to be updated to reflect this if you are using pods?

Thanks, this works for me

**Comment by FrozenIce0617** [comment]
Hi, @blackpencil8994 

So manual link of `react-native-gesture-handler` is a must?
Please let me know.

Thanks.

**Comment by M1seRy** [comment]
@joshverd wise decision，I almost want to buy another new mbp to try solve this issue .🤷‍♀️

**Comment by volokolamskspb** [comment]
> > I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> > `react-native link react-native-gesture-handler`
> > I then had to run
> > `pod install`
> > Maybe the instructions need to be updated to reflect this if you are using pods?

`npm install --save react-native-gesture-handler`
`react-native link react-native-gesture-handler`
`cd /ios`
`pod install`

Also works for me on MacOS with versions: `react-native-cli: 2.0.1; react-native: 0.60.0`
I'm running into this error in each new project.

**Comment by Dror-Bar** [comment]
> Looks like this is to do with the new autolinking feature in RN 0.60. To fix for now just add the following podspec for RNGesureHandler to ios/Podfile
> 
> ```
> pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
> ```
> 
> Then in the ios directory run pod install to install it.

This, and this again. Please update the installing instructions to include this.
On a side note, I don't understand why we have to use cocoapods in RN 6.0.

**Comment by KellyUK** [comment]
> This thing worked for me:
> Go to `node_modules/react-native-gesture-handler/GestureHandler.js`
> And commit this line
> `//export { default as Directions } from './Directions';`

Thank you. If you comment out the line above it works.

**Comment by liyamahendra** [comment]
None of the above solutions of adding to the library and build phases worked for me. Following is what worked for me:

```
cd ios
pod install
```

Original credits [here](https://github.com/kmagiera/react-native-gesture-handler/issues/676#issuecomment-509634511).

**Comment by AidenChen** [comment]
I fixed it by:
> npm i jetifier -D
> npx jetify

**Comment by schwamic** [comment]
@blackpencil8994 
> Finally I did the same with new project and it worked for me.
> 
> So we need to **manual linking** `react-native-gesture-handler` with this new version
> 
> Thank you all.

### iOS
`react-native link react-native-gesture-handler` did not work for iOS. I checked the Libraries folder in XCode and `RNGestureHandler.xcodeproj` was not listed. After following this steps [react-native/docs](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) iOS worked for me.

### Android
Im am using ReactNative v0.59.10 and this version doesn't support AndroidX. Therefore you should not use [jetifier](https://github.com/mikehardy/jetifier), I think this is for RN.0.60+ which supports AndroidX. If you only follow the [ReactNavigation guide](https://reactnavigation.org/docs/en/getting-started.html) without the jetifier step, it works perfekt for Android out of the box.

**Comment by jslyonnais** [comment]
> In react-native v0.60.0 RC 0 i had to run pod install in the ios directory and it worked fine.
> I was getting the same error with just react-native link.

The `pod install` inside `ios` folder works really great! The things is it's really inconvenient for future work and colleague.

Try adding a npm script like `"install": "yarn && cd ios && pod install"` or something to make sure people of your team don't have the same issue.

**Comment by jackvial** [comment]
I had deleted the TVOS targets in xCode so Pod install was throwing an error, I deleted the TVOS folders from `ios/` and removed the target checks for TVOS from the pod file, then ran pod install, rebuilt from xCode and that fixed the error.

**Comment by ramanasak** [comment]
I am having the same issue ,I am using react-native version 0.60.3 , in docs it says automatic linking in react-native 0.60 above version . what should i do ?

![image](https://user-images.githubusercontent.com/24754280/61458160-7d565600-a987-11e9-82a3-567f6c812725.png)

**Comment by nicolastanski** [comment]
> > > I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> > > `react-native link react-native-gesture-handler`
> > > I then had to run
> > > `pod install`
> > > Maybe the instructions need to be updated to reflect this if you are using pods?
> 
> `npm install --save react-native-gesture-handler`
> `react-native link react-native-gesture-handler`
> `cd /ios`
> `pod install`
> 
> Also works for me on MacOS with versions: `react-native-cli: 2.0.1; react-native: 0.60.0`
> I'm running into this error in each new project.

It works for me. Thanks.

**Comment by ramanasak** [comment]
@nicolastanski  I am using windows environment , does this work for  window
npm install --save react-native-gestur-handler
react-native link react-native-gesture-handler

**Comment by ramanasak** [comment]
@nicolastanski i have used these  commands earlier to install 

npm install react-navigation
npm install react-navigation-gesture-handler

**Comment by bagasroman** [comment]
see your native react version, if version 0.60 then you must migrate to androidX using a jetifier, follow the steps in this link
https://github.com/mikehardy/jetifier

successful for me :)

**Comment by XeeshanAnsari** [comment]
in react-native 0.60.+ you will have to install pod.
`cd ios && pod install && cd ../`

**Comment by valnavarro** [comment]
thanks @volokolamskspb

**Comment by ma-lemire** [comment]
@Harsh2402 I love you man ! works well

**Comment by Saroopashree** [comment]
> Have you tried this? This solved my problem
> 
> 1. Right Click Libraries "Add Files to Project"
> 2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 3. Go to build phases and add libRNGestureHandler.a
> 4. Run
>    Good luck to you all!


What is that **Libraries**? I can't understand the step 1. 
Also where to add the libRNGestureHandler.a
In the Xcode project I can't add the libRNGestureHandler.a file in the Target Dependencies. Only the libRNGestureHandler-tvOS.a file is available to add in the Target Dependencies.

**_Help me out._**

**Comment by lakkansingh** [comment]
> > > > I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> > > > `react-native link react-native-gesture-handler`
> > > > I then had to run
> > > > `pod install`
> > > > Maybe the instructions need to be updated to reflect this if you are using pods?
> > 
> > 
> > `npm install --save react-native-gesture-handler`
> > `react-native link react-native-gesture-handler`
> > `cd /ios`
> > `pod install`
> > Also works for me on MacOS with versions: `react-native-cli: 2.0.1; react-native: 0.60.0`
> > I'm running into this error in each new project.
> 
> It works for me. Thanks.

>It works for me. Thanks

**Comment by zhumanasyrov** [comment]
I did like this: 
1. cd ios 
2. pod init
3. pod install (RNGesture is download) success
4. turn off every session and after again set on terminal react-native run-ios 
For me this solution is worked
Thank for everything who helped!

**Comment by erwinwahyura** [comment]
i solved my issue by did this
in ios if you already `cd ios && pod install` re run the project `react-native run-ios`

**Comment by eddskt** [comment]
> @amrita6 you can link automatically in Android. But you need to manual link in iOS project.
> After install package, try this:
> 
> 1. Manual link for iOS project in XCode
> 2. Rename **ios** folder into **iosX**
> 3. Automatically link for Android by `react-native link react-native-gesture-handler`
> 4. Rename  **iosX** folder into **ios** in turn
> 5. Run
> 
> Hope this helps.

How to manual link for ios? in the docs say: 

> iOS
> There is no additional configuration required on iOS except what follows in the next steps.

**Comment by fmonvoisin** [comment]
Compiling further answers from this feed, I did the following for android :
`react-native link reat-native-gesture-handler`

In your `build.gradle` be sure to have the following : 
`implementation project(':react-native-gesture-handler')`

In your `settings.gradle` be sure to have the following : 
```
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
```

In your `MainApplication.java` be sure to have the following:
```
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
...
new MainReactPackage(),
            ...
            new RNGestureHandlerPackage()
```

I made a lot of upgrades for my react native libraries so I had to change all my calls to `StackNavigator `into `createStackNavigator`

**Comment by biranchi2018** [comment]
> ```
> pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
> ```

The dependency `RNGestureHandler (from `../node_modules/react-native-gesture-handler/RNGestureHandler.podspec`)` is not used in any concrete target.

**Comment by cwilby** [comment]
> I may have the answer to this!!!!
> 
> I was in some of my ES6 constants file... and I added a TouchableOpacity by accident, instead of the usual TouchableHighlight in some JSX.
> 
> My editor (Visual Studio Code) seemed to have added:
> `import { TouchableOpacity } from 'react-native-gesture-handler';`
> at the top of my file!!! WIthout my asking for it!
> 
> Go see if this was put into your code by accident, got the same error as all of you! Nothing to do with some of these comments!
> 
> It also puts an erronous console import as well when i use console for the first time in a file!
> 
> Anyway, had the error, noticed the bad import at the top and now all ok!!!

I thought this was the case too, but turns out this library provides their own versions of Touchable components: https://software-mansion.github.io/react-native-gesture-handler/docs/component-touchables.html

**Comment by AnkitaSrivastav** [comment]
I am trying to integrate my existing android app with react native and getting the same error. Do I need to add anything to my application class?

**Comment by ahsan-khan1999** [comment]
just unlink react native from react native gesture handler and rebuild the project.

**Comment by juanlet** [comment]
You can also add a clean script and use the  react-native-clean-project package, make sure you wipe everything when the the clean command prompts you to choose whether to wipe or not ios folder, etc.....Uninstall the app on the device and the run it again

 "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "clean": "react-native-clean-project"
  },

**Comment by BisratYalew** [comment]
I am using "react-native": "0.61.5"
I am working on ubuntu 18.04
I fixed the issue on my android emulator by following the steps mentioned below

Make sure you follow steps for the version you are using (React Native 0.61.5 and lower in my case)

1) Delete/Remove your node_modules directory
`rm -rf node_modules`

2) Install your dependencies again
If you are using Yarn `$ yarn` or `npm install` if you are using npm

3) Clean your Gradle
I followed below steps for that:

`cd android`
`./gradlew clean`
`cd ..`
`react-native run-android`

Good Luck, These steps worked for me

**Comment by epitaci0** [comment]
From the basics, remember to always install dependencies with --save at the end.
example:
yarn add @ react-navigation / native --save

That solved my problem, but if it persists try react-native run-android or run-ios

Usually this already solves, changes in the android folder without the person's documentation is very dangerous and if done wrong it can corrupt your project

Note: Grammatical errors are due to the fact that I am using the google translator to answer, my english for conversation is not very good. ; D

Hope this helps

**Comment by jonson-ncube** [comment]
This should fix your issue

rm -rf ios/Pods && rm -rf ios/build && cd ios && pod install && cd ../

rm -rf node_modules && rm yarn.lock && yarn install

**Comment by codyi96** [comment]
> I had this issue with iOS when trying to get it running. After following the installation instructions and linking with
> 
> `react-native link react-native-gesture-handler`
> 
> I then had to run
> 
> `pod install`
> 
> Maybe the instructions need to be updated to reflect this if you are using pods?

It works for me! thank u! 😀

**Comment by kirilkirkov** [comment]
> in react-native 0.60.+ you will have to install pod.
> `cd ios && pod install && cd ../`

Right solution

**Comment by KEMBL** [comment]
Who has that problem in Android - it looks like related to auto-linking which does not happen, try to check why as described: https://stackoverflow.com/a/61218793/6152462

**Comment by mmorcc** [comment]
i run it in android and ios  
"react-native-router-flux": "^3.37.0"
just npm i react-native-router-flux
 react-native run-ios/android

**Comment by sonuKumar03** [comment]
for android 
install the required packes and run 
"npx react-native link"

**Comment by vicary** [comment]
@XeeshanAnsari thanks for the suggestion, https://github.com/software-mansion/react-native-gesture-handler/issues/494#issuecomment-513963594 should really be documented in [Getting Started](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html)!

**Comment by IsaacValdivia** [comment]
Still happening to me in Android... Unlinking and relinking, cleaning gradle, executing on physical device or emulator, cleaning node_modules, starting with an empty react native project... None of that works

**Comment by kemalony** [comment]
npx pod-install ios
solved my issue
https://reactnavigation.org/docs/getting-started

**Comment by mjohns39** [comment]
For the monsoon of people that are going to run into this issue and spend hour(s) scratching their head, `npx pod-install ios` solved the issue for me (too).

package.json:
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.4.3",
    "@react-navigation/stack": "^5.4.0",
    "axios": "^0.19.2",
    "native-base": "^2.13.12",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^2.0.0",
    "react-native-screens": "^2.8.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-redux": "^7.1.8",
    "@types/react-test-renderer": "16.9.2",
    "@types/redux-logger": "^3.0.7",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
```

**Comment by khanof89** [comment]
did you run pod install in ios directory ?

**Comment by NoComment73** [comment]
I was stuck with this error under iOS (simulator) until I removed the app from the simulator device. stopped the simulator and launched it again with `react-native run-ios`. Didn't need to do this on my "real" device though, even though it's still in develop mode there.

**Comment by utsavshukla0509** [comment]
> Finally I did the same with new project and it worked for me.
> 
> So we need to **manual linking** `react-native-gesture-handler` with this new version
> 
> Thank you all.

Its working fine when this command is run "react-native link"

**Comment by brij-dev** [comment]
Umm... In my case I forgot to install pods :)
just do 
`cd ios `
`pod install`
then try 
`react-native run-ios`
ॐ

**Comment by UsaMaH11** [comment]
I was facing the same error in android.
 solved this by linking manually.
after installing dependencies
1: run react-native link react-native-gesture-handler
2: rebuild the project react-native run android
after build 
3:react-native start
You are good to go..
thanks

**Comment by Krishnarajsalim** [comment]
npm i react-navigation @react-native-community/masked-view react-native-gesture-handler react-native-reanimated react-native-safe-area-context react-native-screens

Nvm install react-navigation-stack

cd ios
pod install
cd ..

It worked for me... :)

**Comment by supritshah1289** [comment]
IOS Steps that worked for me

1. `react-native link react-native-gesture-handler`
2. ios directory `pod install --repo-update`
3. close ios simulator 
4. `react-native run-ios`

**Comment by codeibrahima** [comment]
> IOS Steps that worked for me
> 
> 1. `react-native link react-native-gesture-handler`
> 2. ios directory `pod install --repo-update`
> 3. close ios simulator
> 4. `react-native run-ios`

Also worked for me.. Thx

**Comment by pgThiago** [comment]
I finally fixed by reconnecting my android phone via USB and running "npx react-native run-android" again.
Looks like it was recompiling or was needed to download a few things. 
Now i'm wondering why my app is running even tho i didn't import: "import 'react-native-gesture-handler". 
I'll see if it's really necessary later.

**Comment by slykar** [comment]
@pgThiago in the docs you can find following statement:

> Note: If you skip this step, your app may crash in production even if it works fine in development.

https://reactnavigation.org/docs/getting-started

**Comment by iHakan** [comment]
For the ones who are still having this issue, reactnavigation.org  released a troubleshooting topic for this specific error, here is the link;
https://reactnavigation.org/docs/troubleshooting 

I hope this will help you!

**Comment by benwzj** [comment]
it work for me , thanks!

**Comment by jakub-gonet** [comment]
Thanks for the link @iHakan, I think we can close this one.

**Comment by jakub-gonet** [comment]
Oh, it was closed, nevermind 😄

**Comment by hallowcard13** [comment]
> @amrita6 you can link automatically in Android. But you need to manual link in iOS project.
> After install package, try this:
> 
> 1. Manual link for iOS project in XCode
> 2. Rename **ios** folder into **iosX**
> 3. Automatically link for Android by `react-native link react-native-gesture-handler`
> 4. Rename  **iosX** folder into **ios** in turn
> 5. Run
> 
> Hope this helps.

HI can you please explain the first method, sorry i'm new into React Native

**Comment by Mubeyd** [comment]
run cd android && ./gradlew clean before react-native run-android 
:)

**Comment by mariohmol** [comment]
Still with this issue even after following the throublshooting, which asks for unlink.. but i've seen solutions here asking to link and didn't work 

````
[Fri Sep 25 2020 17:24:47.710]  BUNDLE  ./index.js 

[Fri Sep 25 2020 17:25:07.300]  ERROR    TypeError: undefined is not an object (evaluating '_RNGestureHandlerModule.default.Direction')
[Fri Sep 25 2020 17:25:07.301]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Fri Sep 25 2020 17:25:07.302]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by rizwanellahi** [comment]
> Still with this issue even after following the throublshooting, which asks for unlink.. but i've seen solutions here asking to link and didn't work
> 
> ```
> [Fri Sep 25 2020 17:24:47.710]  BUNDLE  ./index.js 
> 
> [Fri Sep 25 2020 17:25:07.300]  ERROR    TypeError: undefined is not an object (evaluating '_RNGestureHandlerModule.default.Direction')
> [Fri Sep 25 2020 17:25:07.301]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
> [Fri Sep 25 2020 17:25:07.302]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
> ```
> ```

Facing the same issue.

**Comment by mariohmol** [comment]
@rizwanellahi what I did was finding a working example on web and work from there... if u try to setup from scratch following the docs u will face this issue

**Comment by tiendq** [comment]
> run cd android && ./gradlew clean before react-native run-android
> :)

Thank you, the most simple trick here, it worked like a charm :)

**Comment by daydreaminblue** [comment]
if none of answers worked, just assume that you must : 
remove react-native-cli package globally (if you started project with npx react-native init)
and delete system gradle cache (for windows : C:\Users\[username]\.gradle\caches)

**Comment by oguzhancelikarslan** [comment]
> react-native link

great!

**Comment by purplecones** [comment]
For what it's worth, I had the same issue but only for Android. In my case, I jumped into an existing codebase that was initially only built for iOS with the goal of making the app work on Android as well. To resolve this issue, I had to update the `react-native.config.js` file and comment out the following:
```
module.exports = {
  dependencies: {
    // 'react-native-gesture-handler': {
    //   platforms: {
    //     android: null,
    //     ios: null,
    //   },
    // },
  },
};
```

Not sure why this was added to begin with but it resolved the error above. Now both Android and iOS builds load up fine.

**Comment by Sayyamabbasi786** [comment]
> import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;

went into new error of Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager android error

**Comment by jakub-gonet** [comment]
I'm locking this issue due to spam. Please open a new issue with a reproducible example if this problem still exists.
