### ISSUE TITLE
Swipeable is not working on android

### ISSUE THREAD

**Issue by JohnGkouziotis** [software-mansion/react-native-gesture-handler#725]
So i'm trying to use the Swipeable component from react-native-gesture-handler. The thing is that it does nothing. Below is my code

App.js

```
import Swipeable from 'react-native-gesture-handler/Swipeable';

const RightActions = () => {
  return (
    <TouchableOpacity onPress={() => console.warn('works'))}>
      <Icon name="md-trash" size={18} color={Colors.red} />
    </TouchableOpacity>
  );
};

const App = () => {
  return (
    <ScrollView>
    ...
      {Object.keys(data).map(key => {
        return (
          <Swipeable key={key} renderRightActions={RightActions}>
            <View>
              <Text>Swipe left</Text>
            </View>
          </Swipeable>
        );
      });
    </ScrollView>
  );
};

export default App;
```

And here is my MainActivity.java as it is suggested.

```
package com.assosfood;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "assosfood";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}

```

This is all done with react-native not with expo. What am i doing wrong?

**Comment by Albert0405** [comment]
react-navigation uses this library for their drawer navigation. We have the same similar problem. The problem happens in `v0.60.4`. What's your RN version by the way?

**Comment by JohnGkouziotis** [comment]
My version is ```v0. 60.4``` as well. I thought I was doing something wrong.

**Comment by Vijay-mRoads** [comment]
Facing the same issue. My version is v0.60.4 as well

**Comment by voxspox** [comment]
+1

**Comment by leabaertschi** [comment]
Not working with v0.60.5 either

**Comment by josephmbeveridge** [comment]
We are still having this issue on 0.61.0-rc2. Is this still one the radar for being fixed?

**Comment by netgfx** [comment]
Yes same issue here, local code doesn't work with react navigation drawer, but here with Expo it does https://snack.expo.io/@netgfx/auth-flow-v3 any ideas?

**Comment by rkstar** [comment]
apparently this was fixed in RN 0.61.1

**Comment by juniorstreichan** [comment]
I´m using inside the Flatlist component, it's ok

https://stackoverflow.com/questions/57428224/react-native-gesture-handler-swipeable-is-not-working-on-android

**Comment by mnemanja** [comment]
I can say that in RN 0.61.1 it still exists.
The drawer opens, but it cannot be clicked away or swiped.

By the way, I'm not using Swipeable, but a regular `createDrawerNavigator`.

**Comment by juniorstreichan** [comment]
In version 4 of react-navigation, separate navigations

https://reactnavigation.org/docs/en/drawer-navigator.html#api

**Comment by MariShielaFurio** [comment]
This helps me to make swipeable working.
https://aboutreact.com/swipe-gestures-not-working-in-android/

**Comment by lyair1** [comment]
You'll have to modify MainActivity.java:

Add:

`import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

@Override
protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
    	@Override
      	protected ReactRootView createRootView() {
       		return new RNGestureHandlerEnabledRootView(MainActivity.this);
      	}
    };
}`

**Comment by Yandamuri** [comment]
@MariShielaFurio Worked this solution for me.......Thank You

**Comment by EricLewe** [comment]
For the ones using react-native-navigation (RNN). You should instead follow this part of the doc:
https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation

**Comment by jakub-gonet** [comment]
Should be resolved.

**Comment by being-yash-t** [comment]
> For the ones using react-native-navigation (RNN). You should instead follow this part of the doc:
> https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation

Amm, I am having the same issue. the gesture isn't working.
Also, I am using react-navigation - native.
New to react native, using Flat List.
Need help

**Comment by jakub-gonet** [comment]
Try following installation instructions at updated link
https://docs.swmansion.com/react-native-gesture-handler/docs

**Comment by Decoder3-14** [comment]
> This helps me to make swipeable working.
> https://aboutreact.com/swipe-gestures-not-working-in-android/

That was the solution in my case w/ Navigation 5. I noticed it worked after gradlew clean and then rebuild

**Comment by zikyfranky** [comment]
So I made use of RN FlatList

To get it working on Android, I just had to wrap FlatList with <GestureHandlerRootView>

**Comment by Kotpes** [comment]
> So I made use of RN `FlatList`
> 
> To get it working on Android, I just had to wrap `FlatList` with `<GestureHandlerRootView>`

I've had a separate issue where `Swipeable` won't properly work when inside of the `renderItem` of a `FlatList` due to scroll kicking in and swipeable gesture is dropped. But this solution totally solved it! Thanks!
